= Reserved URI Schemes

NeoEMF relies on EMF's URI schemes to understand which backend to instantiate from a given resource URI.
This page summarizes the current supported schemes and their corresponding backend.

According to the NeoEMF link:Naming-Conventions[code conventions] schemes are defined in dedicated `UriBuilder` subclasses.
Note that URI schemes also start with the `neo` prefix to avoid name clashes.
Please follow these guidelines if you want to link:Create-A-New-Module[create a new module].

[NOTE]
====
URI schemes are automatically processed by the binding engine that associate a URI scheme with the name of its associated `BackendFactory`.
In a common use, you should not create your own URI scheme.
====

|===
| Scheme | Backend

| `neo-im`
| Default in-memory database

| `neo-blueprints`
| Blueprints^<<fn1,1>>^

| `neo-mapdb`
| MapDB

| `neo-berkeleydb`
| BerkeleyDB

| `neo-hbase`
| HBase
|===

^1^
TinkerGraph and Neo4j implementations are based on Blueprints and are accessed with the same URI scheme.
Don't forget to use the `Config` implementation of the module you want to use.
