<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.atlanmod.neoemf.eclipse</groupId>
        <artifactId>org.atlanmod.neoemf.eclipse.configuration</artifactId>
        <version>2.1.1-SNAPSHOT</version>
        <relativePath>releng/configuration</relativePath>
    </parent>

    <artifactId>org.atlanmod.neoemf.eclipse</artifactId>

    <packaging>pom</packaging>

    <name>NeoEMF Eclipse</name>
    <description/>

    <modules>
        <module>bundles</module>
        <module>features</module>
        <module>examples</module>
        <module>releng</module>
    </modules>


    <dependencies>
        <dependency>
            <!-- Added to solve dependency problem to osgi.extender
                (&(osgi.extender=osgi.component)(version>=1.4.0)(!(version>=2.0.0))) -->
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.scr</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.scr</artifactId>
                <version>2.2.14</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-core</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-io</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-data-berkeleydb</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-data-blueprints-core</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-data-blueprints-neo4j</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-data-hbase</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.atlanmod.neoemf</groupId>
                <artifactId>neoemf-data-mapdb</artifactId>
                <version>${neoemf.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
