<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sample" nsURI="http://www.neoemf.com/tests/sample" nsPrefix="sample">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelDirectory" value="/fr.inria.atlanmod.neoemf.tests.sample/src"/>
    <details key="rootExtendsInterface" value="fr.inria.atlanmod.neoemf.core.PersistentEObject"/>
    <details key="rootExtendsClass" value="fr.inria.atlanmod.neoemf.core.DefaultPersistentEObject"/>
    <details key="importerID" value="fr.inria.atlanmod.neoemf.eclipse.ui.importer.NeoModelImporter"/>
    <details key="bundleManifest" value="false"/>
    <details key="reflectiveDelegation" value="true"/>
    <details key="featureDelegation" value="Reflective"/>
    <details key="basePackage" value="fr.inria.atlanmod.neoemf.tests"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
