
/**
 * Copyright (c) 2013 Atlanmod INRIA LINA Mines Nantes
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *    Atlanmod INRIA LINA Mines Nantes - initial API and implementation
 * Descritpion ! To come
 * @author Amine BENELALLAM
**/
package org.eclipse.gmt.modisco.java.neo4emf.reltypes;

import org.neo4j.graphdb.RelationshipType;
/**
 * <!-- begin-user-doc -->
 * Neo4j <b>relationships</b> for model persistence.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @generated
 */
public enum Reltypes implements RelationshipType {
	
    		AST_NODE__COMMENTS,
    		
    		AST_NODE__ORIGINAL_COMPILATION_UNIT,
    		
    		AST_NODE__ORIGINAL_CLASS_FILE,
    		
    		NAMED_ELEMENT__COMMENTS,
    		
    		NAMED_ELEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		NAMED_ELEMENT__ORIGINAL_CLASS_FILE,
    		
    		NAMED_ELEMENT__USAGES_IN_IMPORTS,
    		
    		BODY_DECLARATION__COMMENTS,
    		
    		BODY_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		BODY_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		BODY_DECLARATION__USAGES_IN_IMPORTS,
    		
    		BODY_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		BODY_DECLARATION__ANNOTATIONS,
    		
    		BODY_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		BODY_DECLARATION__MODIFIER,
    		
    		ABSTRACT_METHOD_DECLARATION__COMMENTS,
    		
    		ABSTRACT_METHOD_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ABSTRACT_METHOD_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ABSTRACT_METHOD_DECLARATION__USAGES_IN_IMPORTS,
    		
    		ABSTRACT_METHOD_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		ABSTRACT_METHOD_DECLARATION__ANNOTATIONS,
    		
    		ABSTRACT_METHOD_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		ABSTRACT_METHOD_DECLARATION__MODIFIER,
    		
    		ABSTRACT_METHOD_DECLARATION__BODY,
    		
    		ABSTRACT_METHOD_DECLARATION__PARAMETERS,
    		
    		ABSTRACT_METHOD_DECLARATION__THROWN_EXCEPTIONS,
    		
    		ABSTRACT_METHOD_DECLARATION__TYPE_PARAMETERS,
    		
    		ABSTRACT_METHOD_DECLARATION__USAGES_IN_DOC_COMMENTS,
    		
    		ABSTRACT_METHOD_DECLARATION__USAGES,
    		
    		ABSTRACT_METHOD_INVOCATION__COMMENTS,
    		
    		ABSTRACT_METHOD_INVOCATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ABSTRACT_METHOD_INVOCATION__ORIGINAL_CLASS_FILE,
    		
    		ABSTRACT_METHOD_INVOCATION__METHOD,
    		
    		ABSTRACT_METHOD_INVOCATION__ARGUMENTS,
    		
    		ABSTRACT_METHOD_INVOCATION__TYPE_ARGUMENTS,
    		
    		ABSTRACT_TYPE_DECLARATION__COMMENTS,
    		
    		ABSTRACT_TYPE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ABSTRACT_TYPE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ABSTRACT_TYPE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		ABSTRACT_TYPE_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		ABSTRACT_TYPE_DECLARATION__ANNOTATIONS,
    		
    		ABSTRACT_TYPE_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		ABSTRACT_TYPE_DECLARATION__MODIFIER,
    		
    		ABSTRACT_TYPE_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		ABSTRACT_TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		ABSTRACT_TYPE_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		ABSTRACT_TYPE_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		ABSTRACT_TYPE_DECLARATION__PACKAGE,
    		
    		ABSTRACT_TYPE_DECLARATION__SUPER_INTERFACES,
    		
    		EXPRESSION__COMMENTS,
    		
    		EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		ABSTRACT_TYPE_QUALIFIED_EXPRESSION__COMMENTS,
    		
    		ABSTRACT_TYPE_QUALIFIED_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		ABSTRACT_TYPE_QUALIFIED_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		ABSTRACT_TYPE_QUALIFIED_EXPRESSION__QUALIFIER,
    		
    		ABSTRACT_VARIABLES_CONTAINER__COMMENTS,
    		
    		ABSTRACT_VARIABLES_CONTAINER__ORIGINAL_COMPILATION_UNIT,
    		
    		ABSTRACT_VARIABLES_CONTAINER__ORIGINAL_CLASS_FILE,
    		
    		ABSTRACT_VARIABLES_CONTAINER__TYPE,
    		
    		ABSTRACT_VARIABLES_CONTAINER__FRAGMENTS,
    		
    		ANNOTATION__COMMENTS,
    		
    		ANNOTATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ANNOTATION__ORIGINAL_CLASS_FILE,
    		
    		ANNOTATION__TYPE,
    		
    		ANNOTATION__VALUES,
    		
    		ARCHIVE__COMMENTS,
    		
    		ARCHIVE__ORIGINAL_COMPILATION_UNIT,
    		
    		ARCHIVE__ORIGINAL_CLASS_FILE,
    		
    		ARCHIVE__USAGES_IN_IMPORTS,
    		
    		ARCHIVE__CLASS_FILES,
    		
    		ARCHIVE__MANIFEST,
    		
    		STATEMENT__COMMENTS,
    		
    		STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		ASSERT_STATEMENT__COMMENTS,
    		
    		ASSERT_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		ASSERT_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		ASSERT_STATEMENT__MESSAGE,
    		
    		ASSERT_STATEMENT__EXPRESSION,
    		
    		ANNOTATION_MEMBER_VALUE_PAIR__COMMENTS,
    		
    		ANNOTATION_MEMBER_VALUE_PAIR__ORIGINAL_COMPILATION_UNIT,
    		
    		ANNOTATION_MEMBER_VALUE_PAIR__ORIGINAL_CLASS_FILE,
    		
    		ANNOTATION_MEMBER_VALUE_PAIR__USAGES_IN_IMPORTS,
    		
    		ANNOTATION_MEMBER_VALUE_PAIR__MEMBER,
    		
    		ANNOTATION_MEMBER_VALUE_PAIR__VALUE,
    		
    		ANNOTATION_TYPE_DECLARATION__COMMENTS,
    		
    		ANNOTATION_TYPE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ANNOTATION_TYPE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ANNOTATION_TYPE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		ANNOTATION_TYPE_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		ANNOTATION_TYPE_DECLARATION__ANNOTATIONS,
    		
    		ANNOTATION_TYPE_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		ANNOTATION_TYPE_DECLARATION__MODIFIER,
    		
    		ANNOTATION_TYPE_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		ANNOTATION_TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		ANNOTATION_TYPE_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		ANNOTATION_TYPE_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		ANNOTATION_TYPE_DECLARATION__PACKAGE,
    		
    		ANNOTATION_TYPE_DECLARATION__SUPER_INTERFACES,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__COMMENTS,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__USAGES_IN_IMPORTS,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__ANNOTATIONS,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__MODIFIER,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__DEFAULT,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__TYPE,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__USAGES,
    		
    		ANONYMOUS_CLASS_DECLARATION__COMMENTS,
    		
    		ANONYMOUS_CLASS_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ANONYMOUS_CLASS_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ANONYMOUS_CLASS_DECLARATION__BODY_DECLARATIONS,
    		
    		ANONYMOUS_CLASS_DECLARATION__CLASS_INSTANCE_CREATION,
    		
    		ARRAY_ACCESS__COMMENTS,
    		
    		ARRAY_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		ARRAY_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		ARRAY_ACCESS__ARRAY,
    		
    		ARRAY_ACCESS__INDEX,
    		
    		ARRAY_CREATION__COMMENTS,
    		
    		ARRAY_CREATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ARRAY_CREATION__ORIGINAL_CLASS_FILE,
    		
    		ARRAY_CREATION__DIMENSIONS,
    		
    		ARRAY_CREATION__INITIALIZER,
    		
    		ARRAY_CREATION__TYPE,
    		
    		ARRAY_INITIALIZER__COMMENTS,
    		
    		ARRAY_INITIALIZER__ORIGINAL_COMPILATION_UNIT,
    		
    		ARRAY_INITIALIZER__ORIGINAL_CLASS_FILE,
    		
    		ARRAY_INITIALIZER__EXPRESSIONS,
    		
    		ARRAY_LENGTH_ACCESS__COMMENTS,
    		
    		ARRAY_LENGTH_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		ARRAY_LENGTH_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		ARRAY_LENGTH_ACCESS__ARRAY,
    		
    		TYPE__COMMENTS,
    		
    		TYPE__ORIGINAL_COMPILATION_UNIT,
    		
    		TYPE__ORIGINAL_CLASS_FILE,
    		
    		TYPE__USAGES_IN_IMPORTS,
    		
    		TYPE__USAGES_IN_TYPE_ACCESS,
    		
    		ARRAY_TYPE__COMMENTS,
    		
    		ARRAY_TYPE__ORIGINAL_COMPILATION_UNIT,
    		
    		ARRAY_TYPE__ORIGINAL_CLASS_FILE,
    		
    		ARRAY_TYPE__USAGES_IN_IMPORTS,
    		
    		ARRAY_TYPE__USAGES_IN_TYPE_ACCESS,
    		
    		ARRAY_TYPE__ELEMENT_TYPE,
    		
    		ASSIGNMENT__COMMENTS,
    		
    		ASSIGNMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		ASSIGNMENT__ORIGINAL_CLASS_FILE,
    		
    		ASSIGNMENT__LEFT_HAND_SIDE,
    		
    		ASSIGNMENT__RIGHT_HAND_SIDE,
    		
    		BOOLEAN_LITERAL__COMMENTS,
    		
    		BOOLEAN_LITERAL__ORIGINAL_COMPILATION_UNIT,
    		
    		BOOLEAN_LITERAL__ORIGINAL_CLASS_FILE,
    		
    		COMMENT__COMMENTS,
    		
    		COMMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		COMMENT__ORIGINAL_CLASS_FILE,
    		
    		BLOCK_COMMENT__COMMENTS,
    		
    		BLOCK_COMMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		BLOCK_COMMENT__ORIGINAL_CLASS_FILE,
    		
    		BLOCK__COMMENTS,
    		
    		BLOCK__ORIGINAL_COMPILATION_UNIT,
    		
    		BLOCK__ORIGINAL_CLASS_FILE,
    		
    		BLOCK__STATEMENTS,
    		
    		BREAK_STATEMENT__COMMENTS,
    		
    		BREAK_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		BREAK_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		BREAK_STATEMENT__LABEL,
    		
    		CAST_EXPRESSION__COMMENTS,
    		
    		CAST_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		CAST_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		CAST_EXPRESSION__EXPRESSION,
    		
    		CAST_EXPRESSION__TYPE,
    		
    		CATCH_CLAUSE__COMMENTS,
    		
    		CATCH_CLAUSE__ORIGINAL_COMPILATION_UNIT,
    		
    		CATCH_CLAUSE__ORIGINAL_CLASS_FILE,
    		
    		CATCH_CLAUSE__EXCEPTION,
    		
    		CATCH_CLAUSE__BODY,
    		
    		CHARACTER_LITERAL__COMMENTS,
    		
    		CHARACTER_LITERAL__ORIGINAL_COMPILATION_UNIT,
    		
    		CHARACTER_LITERAL__ORIGINAL_CLASS_FILE,
    		
    		CLASS_FILE__COMMENTS,
    		
    		CLASS_FILE__ORIGINAL_COMPILATION_UNIT,
    		
    		CLASS_FILE__ORIGINAL_CLASS_FILE,
    		
    		CLASS_FILE__USAGES_IN_IMPORTS,
    		
    		CLASS_FILE__TYPE,
    		
    		CLASS_FILE__ATTACHED_SOURCE,
    		
    		CLASS_FILE__PACKAGE,
    		
    		CLASS_INSTANCE_CREATION__COMMENTS,
    		
    		CLASS_INSTANCE_CREATION__ORIGINAL_COMPILATION_UNIT,
    		
    		CLASS_INSTANCE_CREATION__ORIGINAL_CLASS_FILE,
    		
    		CLASS_INSTANCE_CREATION__METHOD,
    		
    		CLASS_INSTANCE_CREATION__ARGUMENTS,
    		
    		CLASS_INSTANCE_CREATION__TYPE_ARGUMENTS,
    		
    		CLASS_INSTANCE_CREATION__ANONYMOUS_CLASS_DECLARATION,
    		
    		CLASS_INSTANCE_CREATION__EXPRESSION,
    		
    		CLASS_INSTANCE_CREATION__TYPE,
    		
    		CONSTRUCTOR_DECLARATION__COMMENTS,
    		
    		CONSTRUCTOR_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		CONSTRUCTOR_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		CONSTRUCTOR_DECLARATION__USAGES_IN_IMPORTS,
    		
    		CONSTRUCTOR_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		CONSTRUCTOR_DECLARATION__ANNOTATIONS,
    		
    		CONSTRUCTOR_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		CONSTRUCTOR_DECLARATION__MODIFIER,
    		
    		CONSTRUCTOR_DECLARATION__BODY,
    		
    		CONSTRUCTOR_DECLARATION__PARAMETERS,
    		
    		CONSTRUCTOR_DECLARATION__THROWN_EXCEPTIONS,
    		
    		CONSTRUCTOR_DECLARATION__TYPE_PARAMETERS,
    		
    		CONSTRUCTOR_DECLARATION__USAGES_IN_DOC_COMMENTS,
    		
    		CONSTRUCTOR_DECLARATION__USAGES,
    		
    		CONDITIONAL_EXPRESSION__COMMENTS,
    		
    		CONDITIONAL_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		CONDITIONAL_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		CONDITIONAL_EXPRESSION__ELSE_EXPRESSION,
    		
    		CONDITIONAL_EXPRESSION__EXPRESSION,
    		
    		CONDITIONAL_EXPRESSION__THEN_EXPRESSION,
    		
    		CONSTRUCTOR_INVOCATION__COMMENTS,
    		
    		CONSTRUCTOR_INVOCATION__ORIGINAL_COMPILATION_UNIT,
    		
    		CONSTRUCTOR_INVOCATION__ORIGINAL_CLASS_FILE,
    		
    		CONSTRUCTOR_INVOCATION__METHOD,
    		
    		CONSTRUCTOR_INVOCATION__ARGUMENTS,
    		
    		CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS,
    		
    		TYPE_DECLARATION__COMMENTS,
    		
    		TYPE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		TYPE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		TYPE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		TYPE_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		TYPE_DECLARATION__ANNOTATIONS,
    		
    		TYPE_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		TYPE_DECLARATION__MODIFIER,
    		
    		TYPE_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		TYPE_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		TYPE_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		TYPE_DECLARATION__PACKAGE,
    		
    		TYPE_DECLARATION__SUPER_INTERFACES,
    		
    		TYPE_DECLARATION__TYPE_PARAMETERS,
    		
    		CLASS_DECLARATION__COMMENTS,
    		
    		CLASS_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		CLASS_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		CLASS_DECLARATION__USAGES_IN_IMPORTS,
    		
    		CLASS_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		CLASS_DECLARATION__ANNOTATIONS,
    		
    		CLASS_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		CLASS_DECLARATION__MODIFIER,
    		
    		CLASS_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		CLASS_DECLARATION__BODY_DECLARATIONS,
    		
    		CLASS_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		CLASS_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		CLASS_DECLARATION__PACKAGE,
    		
    		CLASS_DECLARATION__SUPER_INTERFACES,
    		
    		CLASS_DECLARATION__TYPE_PARAMETERS,
    		
    		CLASS_DECLARATION__SUPER_CLASS,
    		
    		COMPILATION_UNIT__COMMENTS,
    		
    		COMPILATION_UNIT__ORIGINAL_COMPILATION_UNIT,
    		
    		COMPILATION_UNIT__ORIGINAL_CLASS_FILE,
    		
    		COMPILATION_UNIT__USAGES_IN_IMPORTS,
    		
    		COMPILATION_UNIT__COMMENT_LIST,
    		
    		COMPILATION_UNIT__IMPORTS,
    		
    		COMPILATION_UNIT__PACKAGE,
    		
    		COMPILATION_UNIT__TYPES,
    		
    		CONTINUE_STATEMENT__COMMENTS,
    		
    		CONTINUE_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		CONTINUE_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		CONTINUE_STATEMENT__LABEL,
    		
    		DO_STATEMENT__COMMENTS,
    		
    		DO_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		DO_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		DO_STATEMENT__EXPRESSION,
    		
    		DO_STATEMENT__BODY,
    		
    		EMPTY_STATEMENT__COMMENTS,
    		
    		EMPTY_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		EMPTY_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		ENHANCED_FOR_STATEMENT__COMMENTS,
    		
    		ENHANCED_FOR_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		ENHANCED_FOR_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		ENHANCED_FOR_STATEMENT__BODY,
    		
    		ENHANCED_FOR_STATEMENT__EXPRESSION,
    		
    		ENHANCED_FOR_STATEMENT__PARAMETER,
    		
    		ENUM_CONSTANT_DECLARATION__COMMENTS,
    		
    		ENUM_CONSTANT_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ENUM_CONSTANT_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ENUM_CONSTANT_DECLARATION__USAGES_IN_IMPORTS,
    		
    		ENUM_CONSTANT_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		ENUM_CONSTANT_DECLARATION__ANNOTATIONS,
    		
    		ENUM_CONSTANT_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		ENUM_CONSTANT_DECLARATION__MODIFIER,
    		
    		ENUM_CONSTANT_DECLARATION__INITIALIZER,
    		
    		ENUM_CONSTANT_DECLARATION__USAGE_IN_VARIABLE_ACCESS,
    		
    		ENUM_CONSTANT_DECLARATION__ANONYMOUS_CLASS_DECLARATION,
    		
    		ENUM_CONSTANT_DECLARATION__ARGUMENTS,
    		
    		ENUM_DECLARATION__COMMENTS,
    		
    		ENUM_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		ENUM_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		ENUM_DECLARATION__USAGES_IN_IMPORTS,
    		
    		ENUM_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		ENUM_DECLARATION__ANNOTATIONS,
    		
    		ENUM_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		ENUM_DECLARATION__MODIFIER,
    		
    		ENUM_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		ENUM_DECLARATION__BODY_DECLARATIONS,
    		
    		ENUM_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		ENUM_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		ENUM_DECLARATION__PACKAGE,
    		
    		ENUM_DECLARATION__SUPER_INTERFACES,
    		
    		ENUM_DECLARATION__ENUM_CONSTANTS,
    		
    		EXPRESSION_STATEMENT__COMMENTS,
    		
    		EXPRESSION_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		EXPRESSION_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		EXPRESSION_STATEMENT__EXPRESSION,
    		
    		FIELD_ACCESS__COMMENTS,
    		
    		FIELD_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		FIELD_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		FIELD_ACCESS__FIELD,
    		
    		FIELD_ACCESS__EXPRESSION,
    		
    		FIELD_DECLARATION__COMMENTS,
    		
    		FIELD_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		FIELD_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		FIELD_DECLARATION__USAGES_IN_IMPORTS,
    		
    		FIELD_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		FIELD_DECLARATION__ANNOTATIONS,
    		
    		FIELD_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		FIELD_DECLARATION__MODIFIER,
    		
    		FIELD_DECLARATION__TYPE,
    		
    		FIELD_DECLARATION__FRAGMENTS,
    		
    		FOR_STATEMENT__COMMENTS,
    		
    		FOR_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		FOR_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		FOR_STATEMENT__EXPRESSION,
    		
    		FOR_STATEMENT__UPDATERS,
    		
    		FOR_STATEMENT__INITIALIZERS,
    		
    		FOR_STATEMENT__BODY,
    		
    		IF_STATEMENT__COMMENTS,
    		
    		IF_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		IF_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		IF_STATEMENT__EXPRESSION,
    		
    		IF_STATEMENT__THEN_STATEMENT,
    		
    		IF_STATEMENT__ELSE_STATEMENT,
    		
    		IMPORT_DECLARATION__COMMENTS,
    		
    		IMPORT_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		IMPORT_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		IMPORT_DECLARATION__IMPORTED_ELEMENT,
    		
    		INFIX_EXPRESSION__COMMENTS,
    		
    		INFIX_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		INFIX_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		INFIX_EXPRESSION__RIGHT_OPERAND,
    		
    		INFIX_EXPRESSION__LEFT_OPERAND,
    		
    		INFIX_EXPRESSION__EXTENDED_OPERANDS,
    		
    		INITIALIZER__COMMENTS,
    		
    		INITIALIZER__ORIGINAL_COMPILATION_UNIT,
    		
    		INITIALIZER__ORIGINAL_CLASS_FILE,
    		
    		INITIALIZER__USAGES_IN_IMPORTS,
    		
    		INITIALIZER__ABSTRACT_TYPE_DECLARATION,
    		
    		INITIALIZER__ANNOTATIONS,
    		
    		INITIALIZER__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		INITIALIZER__MODIFIER,
    		
    		INITIALIZER__BODY,
    		
    		INSTANCEOF_EXPRESSION__COMMENTS,
    		
    		INSTANCEOF_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		INSTANCEOF_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		INSTANCEOF_EXPRESSION__RIGHT_OPERAND,
    		
    		INSTANCEOF_EXPRESSION__LEFT_OPERAND,
    		
    		INTERFACE_DECLARATION__COMMENTS,
    		
    		INTERFACE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		INTERFACE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		INTERFACE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		INTERFACE_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		INTERFACE_DECLARATION__ANNOTATIONS,
    		
    		INTERFACE_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		INTERFACE_DECLARATION__MODIFIER,
    		
    		INTERFACE_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		INTERFACE_DECLARATION__BODY_DECLARATIONS,
    		
    		INTERFACE_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		INTERFACE_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		INTERFACE_DECLARATION__PACKAGE,
    		
    		INTERFACE_DECLARATION__SUPER_INTERFACES,
    		
    		INTERFACE_DECLARATION__TYPE_PARAMETERS,
    		
    		JAVADOC__COMMENTS,
    		
    		JAVADOC__ORIGINAL_COMPILATION_UNIT,
    		
    		JAVADOC__ORIGINAL_CLASS_FILE,
    		
    		JAVADOC__TAGS,
    		
    		LABELED_STATEMENT__COMMENTS,
    		
    		LABELED_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		LABELED_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		LABELED_STATEMENT__USAGES_IN_IMPORTS,
    		
    		LABELED_STATEMENT__BODY,
    		
    		LABELED_STATEMENT__USAGES_IN_BREAK_STATEMENTS,
    		
    		LABELED_STATEMENT__USAGES_IN_CONTINUE_STATEMENTS,
    		
    		LINE_COMMENT__COMMENTS,
    		
    		LINE_COMMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		LINE_COMMENT__ORIGINAL_CLASS_FILE,
    		
    		MANIFEST__MAIN_ATTRIBUTES,
    		
    		MANIFEST__ENTRY_ATTRIBUTES,
    		
    		MANIFEST_ENTRY__ATTRIBUTES,
    		
    		MEMBER_REF__COMMENTS,
    		
    		MEMBER_REF__ORIGINAL_COMPILATION_UNIT,
    		
    		MEMBER_REF__ORIGINAL_CLASS_FILE,
    		
    		MEMBER_REF__MEMBER,
    		
    		MEMBER_REF__QUALIFIER,
    		
    		METHOD_DECLARATION__COMMENTS,
    		
    		METHOD_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		METHOD_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		METHOD_DECLARATION__USAGES_IN_IMPORTS,
    		
    		METHOD_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		METHOD_DECLARATION__ANNOTATIONS,
    		
    		METHOD_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		METHOD_DECLARATION__MODIFIER,
    		
    		METHOD_DECLARATION__BODY,
    		
    		METHOD_DECLARATION__PARAMETERS,
    		
    		METHOD_DECLARATION__THROWN_EXCEPTIONS,
    		
    		METHOD_DECLARATION__TYPE_PARAMETERS,
    		
    		METHOD_DECLARATION__USAGES_IN_DOC_COMMENTS,
    		
    		METHOD_DECLARATION__USAGES,
    		
    		METHOD_DECLARATION__RETURN_TYPE,
    		
    		METHOD_DECLARATION__REDEFINED_METHOD_DECLARATION,
    		
    		METHOD_DECLARATION__REDEFINITIONS,
    		
    		METHOD_INVOCATION__COMMENTS,
    		
    		METHOD_INVOCATION__ORIGINAL_COMPILATION_UNIT,
    		
    		METHOD_INVOCATION__ORIGINAL_CLASS_FILE,
    		
    		METHOD_INVOCATION__METHOD,
    		
    		METHOD_INVOCATION__ARGUMENTS,
    		
    		METHOD_INVOCATION__TYPE_ARGUMENTS,
    		
    		METHOD_INVOCATION__EXPRESSION,
    		
    		METHOD_REF__COMMENTS,
    		
    		METHOD_REF__ORIGINAL_COMPILATION_UNIT,
    		
    		METHOD_REF__ORIGINAL_CLASS_FILE,
    		
    		METHOD_REF__METHOD,
    		
    		METHOD_REF__QUALIFIER,
    		
    		METHOD_REF__PARAMETERS,
    		
    		METHOD_REF_PARAMETER__COMMENTS,
    		
    		METHOD_REF_PARAMETER__ORIGINAL_COMPILATION_UNIT,
    		
    		METHOD_REF_PARAMETER__ORIGINAL_CLASS_FILE,
    		
    		METHOD_REF_PARAMETER__TYPE,
    		
    		MODEL__OWNED_ELEMENTS,
    		
    		MODEL__ORPHAN_TYPES,
    		
    		MODEL__UNRESOLVED_ITEMS,
    		
    		MODEL__COMPILATION_UNITS,
    		
    		MODEL__CLASS_FILES,
    		
    		MODEL__ARCHIVES,
    		
    		MODIFIER__COMMENTS,
    		
    		MODIFIER__ORIGINAL_COMPILATION_UNIT,
    		
    		MODIFIER__ORIGINAL_CLASS_FILE,
    		
    		MODIFIER__BODY_DECLARATION,
    		
    		MODIFIER__SINGLE_VARIABLE_DECLARATION,
    		
    		MODIFIER__VARIABLE_DECLARATION_STATEMENT,
    		
    		MODIFIER__VARIABLE_DECLARATION_EXPRESSION,
    		
    		NAMESPACE_ACCESS__COMMENTS,
    		
    		NAMESPACE_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		NAMESPACE_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		NUMBER_LITERAL__COMMENTS,
    		
    		NUMBER_LITERAL__ORIGINAL_COMPILATION_UNIT,
    		
    		NUMBER_LITERAL__ORIGINAL_CLASS_FILE,
    		
    		NULL_LITERAL__COMMENTS,
    		
    		NULL_LITERAL__ORIGINAL_COMPILATION_UNIT,
    		
    		NULL_LITERAL__ORIGINAL_CLASS_FILE,
    		
    		PACKAGE__COMMENTS,
    		
    		PACKAGE__ORIGINAL_COMPILATION_UNIT,
    		
    		PACKAGE__ORIGINAL_CLASS_FILE,
    		
    		PACKAGE__USAGES_IN_IMPORTS,
    		
    		PACKAGE__OWNED_ELEMENTS,
    		
    		PACKAGE__MODEL,
    		
    		PACKAGE__OWNED_PACKAGES,
    		
    		PACKAGE__PACKAGE,
    		
    		PACKAGE__USAGES_IN_PACKAGE_ACCESS,
    		
    		PACKAGE_ACCESS__COMMENTS,
    		
    		PACKAGE_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		PACKAGE_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		PACKAGE_ACCESS__PACKAGE,
    		
    		PACKAGE_ACCESS__QUALIFIER,
    		
    		PARAMETERIZED_TYPE__COMMENTS,
    		
    		PARAMETERIZED_TYPE__ORIGINAL_COMPILATION_UNIT,
    		
    		PARAMETERIZED_TYPE__ORIGINAL_CLASS_FILE,
    		
    		PARAMETERIZED_TYPE__USAGES_IN_IMPORTS,
    		
    		PARAMETERIZED_TYPE__USAGES_IN_TYPE_ACCESS,
    		
    		PARAMETERIZED_TYPE__TYPE,
    		
    		PARAMETERIZED_TYPE__TYPE_ARGUMENTS,
    		
    		PARENTHESIZED_EXPRESSION__COMMENTS,
    		
    		PARENTHESIZED_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		PARENTHESIZED_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		PARENTHESIZED_EXPRESSION__EXPRESSION,
    		
    		POSTFIX_EXPRESSION__COMMENTS,
    		
    		POSTFIX_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		POSTFIX_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		POSTFIX_EXPRESSION__OPERAND,
    		
    		PREFIX_EXPRESSION__COMMENTS,
    		
    		PREFIX_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		PREFIX_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		PREFIX_EXPRESSION__OPERAND,
    		
    		PRIMITIVE_TYPE__COMMENTS,
    		
    		PRIMITIVE_TYPE__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_BOOLEAN__COMMENTS,
    		
    		PRIMITIVE_TYPE_BOOLEAN__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_BOOLEAN__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_BOOLEAN__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_BOOLEAN__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_BYTE__COMMENTS,
    		
    		PRIMITIVE_TYPE_BYTE__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_BYTE__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_BYTE__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_BYTE__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_CHAR__COMMENTS,
    		
    		PRIMITIVE_TYPE_CHAR__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_CHAR__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_CHAR__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_CHAR__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_DOUBLE__COMMENTS,
    		
    		PRIMITIVE_TYPE_DOUBLE__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_DOUBLE__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_DOUBLE__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_DOUBLE__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_SHORT__COMMENTS,
    		
    		PRIMITIVE_TYPE_SHORT__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_SHORT__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_SHORT__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_SHORT__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_FLOAT__COMMENTS,
    		
    		PRIMITIVE_TYPE_FLOAT__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_FLOAT__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_FLOAT__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_FLOAT__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_INT__COMMENTS,
    		
    		PRIMITIVE_TYPE_INT__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_INT__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_INT__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_INT__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_LONG__COMMENTS,
    		
    		PRIMITIVE_TYPE_LONG__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_LONG__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_LONG__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_LONG__USAGES_IN_TYPE_ACCESS,
    		
    		PRIMITIVE_TYPE_VOID__COMMENTS,
    		
    		PRIMITIVE_TYPE_VOID__ORIGINAL_COMPILATION_UNIT,
    		
    		PRIMITIVE_TYPE_VOID__ORIGINAL_CLASS_FILE,
    		
    		PRIMITIVE_TYPE_VOID__USAGES_IN_IMPORTS,
    		
    		PRIMITIVE_TYPE_VOID__USAGES_IN_TYPE_ACCESS,
    		
    		RETURN_STATEMENT__COMMENTS,
    		
    		RETURN_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		RETURN_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		RETURN_STATEMENT__EXPRESSION,
    		
    		SINGLE_VARIABLE_ACCESS__COMMENTS,
    		
    		SINGLE_VARIABLE_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		SINGLE_VARIABLE_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		SINGLE_VARIABLE_ACCESS__VARIABLE,
    		
    		SINGLE_VARIABLE_ACCESS__QUALIFIER,
    		
    		VARIABLE_DECLARATION__COMMENTS,
    		
    		VARIABLE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		VARIABLE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		VARIABLE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		VARIABLE_DECLARATION__INITIALIZER,
    		
    		VARIABLE_DECLARATION__USAGE_IN_VARIABLE_ACCESS,
    		
    		SINGLE_VARIABLE_DECLARATION__COMMENTS,
    		
    		SINGLE_VARIABLE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		SINGLE_VARIABLE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		SINGLE_VARIABLE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		SINGLE_VARIABLE_DECLARATION__INITIALIZER,
    		
    		SINGLE_VARIABLE_DECLARATION__USAGE_IN_VARIABLE_ACCESS,
    		
    		SINGLE_VARIABLE_DECLARATION__MODIFIER,
    		
    		SINGLE_VARIABLE_DECLARATION__TYPE,
    		
    		SINGLE_VARIABLE_DECLARATION__ANNOTATIONS,
    		
    		SINGLE_VARIABLE_DECLARATION__METHOD_DECLARATION,
    		
    		SINGLE_VARIABLE_DECLARATION__CATCH_CLAUSE,
    		
    		SINGLE_VARIABLE_DECLARATION__ENHANCED_FOR_STATEMENT,
    		
    		STRING_LITERAL__COMMENTS,
    		
    		STRING_LITERAL__ORIGINAL_COMPILATION_UNIT,
    		
    		STRING_LITERAL__ORIGINAL_CLASS_FILE,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__COMMENTS,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__ORIGINAL_COMPILATION_UNIT,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__ORIGINAL_CLASS_FILE,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__METHOD,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__ARGUMENTS,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__EXPRESSION,
    		
    		SUPER_FIELD_ACCESS__COMMENTS,
    		
    		SUPER_FIELD_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		SUPER_FIELD_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		SUPER_FIELD_ACCESS__QUALIFIER,
    		
    		SUPER_FIELD_ACCESS__FIELD,
    		
    		SUPER_METHOD_INVOCATION__COMMENTS,
    		
    		SUPER_METHOD_INVOCATION__ORIGINAL_COMPILATION_UNIT,
    		
    		SUPER_METHOD_INVOCATION__ORIGINAL_CLASS_FILE,
    		
    		SUPER_METHOD_INVOCATION__QUALIFIER,
    		
    		SUPER_METHOD_INVOCATION__METHOD,
    		
    		SUPER_METHOD_INVOCATION__ARGUMENTS,
    		
    		SUPER_METHOD_INVOCATION__TYPE_ARGUMENTS,
    		
    		SWITCH_CASE__COMMENTS,
    		
    		SWITCH_CASE__ORIGINAL_COMPILATION_UNIT,
    		
    		SWITCH_CASE__ORIGINAL_CLASS_FILE,
    		
    		SWITCH_CASE__EXPRESSION,
    		
    		SWITCH_STATEMENT__COMMENTS,
    		
    		SWITCH_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		SWITCH_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		SWITCH_STATEMENT__EXPRESSION,
    		
    		SWITCH_STATEMENT__STATEMENTS,
    		
    		SYNCHRONIZED_STATEMENT__COMMENTS,
    		
    		SYNCHRONIZED_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		SYNCHRONIZED_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		SYNCHRONIZED_STATEMENT__BODY,
    		
    		SYNCHRONIZED_STATEMENT__EXPRESSION,
    		
    		TAG_ELEMENT__COMMENTS,
    		
    		TAG_ELEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		TAG_ELEMENT__ORIGINAL_CLASS_FILE,
    		
    		TAG_ELEMENT__FRAGMENTS,
    		
    		TEXT_ELEMENT__COMMENTS,
    		
    		TEXT_ELEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		TEXT_ELEMENT__ORIGINAL_CLASS_FILE,
    		
    		THIS_EXPRESSION__COMMENTS,
    		
    		THIS_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		THIS_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		THIS_EXPRESSION__QUALIFIER,
    		
    		THROW_STATEMENT__COMMENTS,
    		
    		THROW_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		THROW_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		THROW_STATEMENT__EXPRESSION,
    		
    		TRY_STATEMENT__COMMENTS,
    		
    		TRY_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		TRY_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		TRY_STATEMENT__BODY,
    		
    		TRY_STATEMENT__FINALLY,
    		
    		TRY_STATEMENT__CATCH_CLAUSES,
    		
    		TYPE_ACCESS__COMMENTS,
    		
    		TYPE_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		TYPE_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		TYPE_ACCESS__TYPE,
    		
    		TYPE_ACCESS__QUALIFIER,
    		
    		TYPE_DECLARATION_STATEMENT__COMMENTS,
    		
    		TYPE_DECLARATION_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		TYPE_DECLARATION_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		TYPE_DECLARATION_STATEMENT__DECLARATION,
    		
    		TYPE_LITERAL__COMMENTS,
    		
    		TYPE_LITERAL__ORIGINAL_COMPILATION_UNIT,
    		
    		TYPE_LITERAL__ORIGINAL_CLASS_FILE,
    		
    		TYPE_LITERAL__TYPE,
    		
    		TYPE_PARAMETER__COMMENTS,
    		
    		TYPE_PARAMETER__ORIGINAL_COMPILATION_UNIT,
    		
    		TYPE_PARAMETER__ORIGINAL_CLASS_FILE,
    		
    		TYPE_PARAMETER__USAGES_IN_IMPORTS,
    		
    		TYPE_PARAMETER__USAGES_IN_TYPE_ACCESS,
    		
    		TYPE_PARAMETER__BOUNDS,
    		
    		UNRESOLVED_ITEM__COMMENTS,
    		
    		UNRESOLVED_ITEM__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_ITEM__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_ITEM__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_ITEM_ACCESS__COMMENTS,
    		
    		UNRESOLVED_ITEM_ACCESS__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_ITEM_ACCESS__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_ITEM_ACCESS__ELEMENT,
    		
    		UNRESOLVED_ITEM_ACCESS__QUALIFIER,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__BODY_DECLARATIONS,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__PACKAGE,
    		
    		UNRESOLVED_ANNOTATION_DECLARATION__SUPER_INTERFACES,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__DEFAULT,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__TYPE,
    		
    		UNRESOLVED_ANNOTATION_TYPE_MEMBER_DECLARATION__USAGES,
    		
    		UNRESOLVED_CLASS_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_CLASS_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_CLASS_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_CLASS_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_CLASS_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_CLASS_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_CLASS_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_CLASS_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_CLASS_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		UNRESOLVED_CLASS_DECLARATION__BODY_DECLARATIONS,
    		
    		UNRESOLVED_CLASS_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		UNRESOLVED_CLASS_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		UNRESOLVED_CLASS_DECLARATION__PACKAGE,
    		
    		UNRESOLVED_CLASS_DECLARATION__SUPER_INTERFACES,
    		
    		UNRESOLVED_CLASS_DECLARATION__TYPE_PARAMETERS,
    		
    		UNRESOLVED_CLASS_DECLARATION__SUPER_CLASS,
    		
    		UNRESOLVED_ENUM_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_ENUM_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_ENUM_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_ENUM_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_ENUM_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_ENUM_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_ENUM_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_ENUM_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_ENUM_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		UNRESOLVED_ENUM_DECLARATION__BODY_DECLARATIONS,
    		
    		UNRESOLVED_ENUM_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		UNRESOLVED_ENUM_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		UNRESOLVED_ENUM_DECLARATION__PACKAGE,
    		
    		UNRESOLVED_ENUM_DECLARATION__SUPER_INTERFACES,
    		
    		UNRESOLVED_ENUM_DECLARATION__ENUM_CONSTANTS,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__BODY_DECLARATIONS,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__PACKAGE,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__SUPER_INTERFACES,
    		
    		UNRESOLVED_INTERFACE_DECLARATION__TYPE_PARAMETERS,
    		
    		UNRESOLVED_LABELED_STATEMENT__COMMENTS,
    		
    		UNRESOLVED_LABELED_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_LABELED_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_LABELED_STATEMENT__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_LABELED_STATEMENT__BODY,
    		
    		UNRESOLVED_LABELED_STATEMENT__USAGES_IN_BREAK_STATEMENTS,
    		
    		UNRESOLVED_LABELED_STATEMENT__USAGES_IN_CONTINUE_STATEMENTS,
    		
    		UNRESOLVED_METHOD_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_METHOD_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_METHOD_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_METHOD_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_METHOD_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_METHOD_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_METHOD_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_METHOD_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_METHOD_DECLARATION__BODY,
    		
    		UNRESOLVED_METHOD_DECLARATION__PARAMETERS,
    		
    		UNRESOLVED_METHOD_DECLARATION__THROWN_EXCEPTIONS,
    		
    		UNRESOLVED_METHOD_DECLARATION__TYPE_PARAMETERS,
    		
    		UNRESOLVED_METHOD_DECLARATION__USAGES_IN_DOC_COMMENTS,
    		
    		UNRESOLVED_METHOD_DECLARATION__USAGES,
    		
    		UNRESOLVED_METHOD_DECLARATION__RETURN_TYPE,
    		
    		UNRESOLVED_METHOD_DECLARATION__REDEFINED_METHOD_DECLARATION,
    		
    		UNRESOLVED_METHOD_DECLARATION__REDEFINITIONS,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__INITIALIZER,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__USAGE_IN_VARIABLE_ACCESS,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__TYPE,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__METHOD_DECLARATION,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__CATCH_CLAUSE,
    		
    		UNRESOLVED_SINGLE_VARIABLE_DECLARATION__ENHANCED_FOR_STATEMENT,
    		
    		UNRESOLVED_TYPE__COMMENTS,
    		
    		UNRESOLVED_TYPE__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_TYPE__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_TYPE__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_TYPE__USAGES_IN_TYPE_ACCESS,
    		
    		UNRESOLVED_TYPE_DECLARATION__COMMENTS,
    		
    		UNRESOLVED_TYPE_DECLARATION__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_TYPE_DECLARATION__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_TYPE_DECLARATION__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_TYPE_DECLARATION__ABSTRACT_TYPE_DECLARATION,
    		
    		UNRESOLVED_TYPE_DECLARATION__ANNOTATIONS,
    		
    		UNRESOLVED_TYPE_DECLARATION__ANONYMOUS_CLASS_DECLARATION_OWNER,
    		
    		UNRESOLVED_TYPE_DECLARATION__MODIFIER,
    		
    		UNRESOLVED_TYPE_DECLARATION__USAGES_IN_TYPE_ACCESS,
    		
    		UNRESOLVED_TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		UNRESOLVED_TYPE_DECLARATION__COMMENTS_BEFORE_BODY,
    		
    		UNRESOLVED_TYPE_DECLARATION__COMMENTS_AFTER_BODY,
    		
    		UNRESOLVED_TYPE_DECLARATION__PACKAGE,
    		
    		UNRESOLVED_TYPE_DECLARATION__SUPER_INTERFACES,
    		
    		VARIABLE_DECLARATION_FRAGMENT__COMMENTS,
    		
    		VARIABLE_DECLARATION_FRAGMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		VARIABLE_DECLARATION_FRAGMENT__ORIGINAL_CLASS_FILE,
    		
    		VARIABLE_DECLARATION_FRAGMENT__USAGES_IN_IMPORTS,
    		
    		VARIABLE_DECLARATION_FRAGMENT__INITIALIZER,
    		
    		VARIABLE_DECLARATION_FRAGMENT__USAGE_IN_VARIABLE_ACCESS,
    		
    		VARIABLE_DECLARATION_FRAGMENT__VARIABLES_CONTAINER,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__COMMENTS,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__ORIGINAL_CLASS_FILE,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__USAGES_IN_IMPORTS,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__INITIALIZER,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__USAGE_IN_VARIABLE_ACCESS,
    		
    		UNRESOLVED_VARIABLE_DECLARATION_FRAGMENT__VARIABLES_CONTAINER,
    		
    		VARIABLE_DECLARATION_EXPRESSION__COMMENTS,
    		
    		VARIABLE_DECLARATION_EXPRESSION__ORIGINAL_COMPILATION_UNIT,
    		
    		VARIABLE_DECLARATION_EXPRESSION__ORIGINAL_CLASS_FILE,
    		
    		VARIABLE_DECLARATION_EXPRESSION__TYPE,
    		
    		VARIABLE_DECLARATION_EXPRESSION__FRAGMENTS,
    		
    		VARIABLE_DECLARATION_EXPRESSION__MODIFIER,
    		
    		VARIABLE_DECLARATION_EXPRESSION__ANNOTATIONS,
    		
    		VARIABLE_DECLARATION_STATEMENT__COMMENTS,
    		
    		VARIABLE_DECLARATION_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		VARIABLE_DECLARATION_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		VARIABLE_DECLARATION_STATEMENT__TYPE,
    		
    		VARIABLE_DECLARATION_STATEMENT__FRAGMENTS,
    		
    		VARIABLE_DECLARATION_STATEMENT__MODIFIER,
    		
    		VARIABLE_DECLARATION_STATEMENT__ANNOTATIONS,
    		
    		WILD_CARD_TYPE__COMMENTS,
    		
    		WILD_CARD_TYPE__ORIGINAL_COMPILATION_UNIT,
    		
    		WILD_CARD_TYPE__ORIGINAL_CLASS_FILE,
    		
    		WILD_CARD_TYPE__USAGES_IN_IMPORTS,
    		
    		WILD_CARD_TYPE__USAGES_IN_TYPE_ACCESS,
    		
    		WILD_CARD_TYPE__BOUND,
    		
    		WHILE_STATEMENT__COMMENTS,
    		
    		WHILE_STATEMENT__ORIGINAL_COMPILATION_UNIT,
    		
    		WHILE_STATEMENT__ORIGINAL_CLASS_FILE,
    		
    		WHILE_STATEMENT__EXPRESSION,
    		
    		WHILE_STATEMENT__BODY,
    		
} 

//Reltypes Class
