<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mgraph" nsURI="http://mgraph/1.1" nsPrefix="mgraphs">
  <eClassifiers xsi:type="ecore:EClass" name="MGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//MNode" containment="true" eOpposite="#//MNode/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//MEdge" containment="true" eOpposite="#//MEdge/graph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inComing" lowerBound="1"
        eType="#//MNode" eOpposite="#//MNode/to"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outGoing" lowerBound="1"
        eType="#//MNode" eOpposite="#//MNode/from"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//MGraph"
        eOpposite="#//MGraph/edges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//MGraph"
        eOpposite="#//MGraph/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-1" eType="#//MEdge"
        eOpposite="#//MEdge/outGoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-1" eType="#//MEdge"
        eOpposite="#//MEdge/inComing"/>
  </eClassifiers>
</ecore:EPackage>
