/**
 *
 * $Id$
 */
package mgraph.validation;

import mgraph.MEdge;
import mgraph.MGraph;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mgraph.MNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MNodeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateGraph(MGraph value);
	boolean validateFrom(EList<MEdge> value);
	boolean validateTo(EList<MEdge> value);
}
