/**
 *
 * $Id$
 */
package reltypes;

import org.neo4j.graphdb.RelationshipType;
/**
 * <!-- begin-user-doc -->
 * Neo4j <b>relationships</b> for model persistence.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @generated
 */
public enum Reltypes implements RelationshipType {
	
    		IJAVA_MODEL__JAVA_PROJECTS,
    		
    		IJAVA_MODEL__EXTERNAL_PACKAGE_FRAGMENT_ROOTS,
    		
    		IJAVA_PROJECT__PACKAGE_FRAGMENT_ROOTS,
    		
    		IJAVA_PROJECT__EXTERNAL_PACKAGE_FRAGMENT_ROOTS,
    		
    		IJAVA_PROJECT__REQUIRED_PROJECTS,
    		
    		IPACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS,
    		
    		BINARY_PACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS,
    		
    		SOURCE_PACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS,
    		
    		IPACKAGE_FRAGMENT__PACKAGE_FRAGMENT_ROOT,
    		
    		IPACKAGE_FRAGMENT__CLASS_FILES,
    		
    		IPACKAGE_FRAGMENT__COMPILATION_UNITS,
    		
    		ITYPE_ROOT__SOURCE_RANGE,
    		
    		ICOMPILATION_UNIT__SOURCE_RANGE,
    		
    		ICOMPILATION_UNIT__ALL_TYPE,
    		
    		ICOMPILATION_UNIT__IMPORTS,
    		
    		ICOMPILATION_UNIT__TYPES,
    		
    		ICOMPILATION_UNIT__PRIMARY,
    		
    		ICOMPILATION_UNIT__AST,
    		
    		ICLASS_FILE__SOURCE_RANGE,
    		
    		ICLASS_FILE__TYPE,
    		
    		ISOURCE_REFERENCE__SOURCE_RANGE,
    		
    		IIMPORT_DECLARATION__SOURCE_RANGE,
    		
    		IMEMBER__SOURCE_RANGE,
    		
    		IMEMBER__JAVADOC_RANGE,
    		
    		IMEMBER__NAME_RANGE,
    		
    		ITYPE__SOURCE_RANGE,
    		
    		ITYPE__JAVADOC_RANGE,
    		
    		ITYPE__NAME_RANGE,
    		
    		ITYPE__INITIALIZERS,
    		
    		ITYPE__FIELDS,
    		
    		ITYPE__METHODS,
    		
    		ITYPE__TYPES,
    		
    		ITYPE__TYPE_PARAMETERS,
    		
    		ITYPE_PARAMETER__SOURCE_RANGE,
    		
    		IINITIALIZER__SOURCE_RANGE,
    		
    		IINITIALIZER__JAVADOC_RANGE,
    		
    		IINITIALIZER__NAME_RANGE,
    		
    		IFIELD__SOURCE_RANGE,
    		
    		IFIELD__JAVADOC_RANGE,
    		
    		IFIELD__NAME_RANGE,
    		
    		IMETHOD__SOURCE_RANGE,
    		
    		IMETHOD__JAVADOC_RANGE,
    		
    		IMETHOD__NAME_RANGE,
    		
    		IMETHOD__PARAMETERS,
    		
    		AST__COMPILATION_UNITS,
    		
    		ANONYMOUS_CLASS_DECLARATION__BODY_DECLARATIONS,
    		
    		BODY_DECLARATION__MODIFIERS,
    		
    		BODY_DECLARATION__JAVADOC,
    		
    		CATCH_CLAUSE__BODY,
    		
    		CATCH_CLAUSE__EXCEPTION,
    		
    		COMMENT__ALTERNATE_ROOT,
    		
    		COMPILATION_UNIT__COMMENTS,
    		
    		COMPILATION_UNIT__PACKAGE,
    		
    		COMPILATION_UNIT__IMPORTS,
    		
    		COMPILATION_UNIT__TYPES,
    		
    		EXPRESSION__TYPE_BINDING,
    		
    		IMPORT_DECLARATION__NAME,
    		
    		MEMBER_REF__NAME,
    		
    		MEMBER_REF__QUALIFIER,
    		
    		MEMBER_VALUE_PAIR__NAME,
    		
    		MEMBER_VALUE_PAIR__VALUE,
    		
    		METHOD_REF__NAME,
    		
    		METHOD_REF__QUALIFIER,
    		
    		METHOD_REF__PARAMETERS,
    		
    		METHOD_REF_PARAMETER__NAME,
    		
    		METHOD_REF_PARAMETER__TYPE,
    		
    		PACKAGE_DECLARATION__ANNOTATIONS,
    		
    		PACKAGE_DECLARATION__JAVADOC,
    		
    		PACKAGE_DECLARATION__NAME,
    		
    		PACKAGE_DECLARATION__BINDING,
    		
    		TAG_ELEMENT__FRAGMENTS,
    		
    		TYPE_PARAMETER__NAME,
    		
    		TYPE_PARAMETER__TYPE_BOUNDS,
    		
    		VARIABLE_DECLARATION__INITIALIZER,
    		
    		VARIABLE_DECLARATION__NAME,
    		
    		ABSTRACT_TYPE_DECLARATION__MODIFIERS,
    		
    		ABSTRACT_TYPE_DECLARATION__JAVADOC,
    		
    		ABSTRACT_TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		ABSTRACT_TYPE_DECLARATION__NAME,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__MODIFIERS,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__JAVADOC,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__DEFAULT,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__NAME,
    		
    		ANNOTATION_TYPE_MEMBER_DECLARATION__TYPE,
    		
    		ENUM_CONSTANT_DECLARATION__MODIFIERS,
    		
    		ENUM_CONSTANT_DECLARATION__JAVADOC,
    		
    		ENUM_CONSTANT_DECLARATION__ARGUMENTS,
    		
    		ENUM_CONSTANT_DECLARATION__ANONYMOUS_CLASS_DECLARATION,
    		
    		ENUM_CONSTANT_DECLARATION__NAME,
    		
    		FIELD_DECLARATION__MODIFIERS,
    		
    		FIELD_DECLARATION__JAVADOC,
    		
    		FIELD_DECLARATION__FRAGMENTS,
    		
    		FIELD_DECLARATION__TYPE,
    		
    		INITIALIZER__MODIFIERS,
    		
    		INITIALIZER__JAVADOC,
    		
    		INITIALIZER__BODY,
    		
    		METHOD_DECLARATION__MODIFIERS,
    		
    		METHOD_DECLARATION__JAVADOC,
    		
    		METHOD_DECLARATION__BODY,
    		
    		METHOD_DECLARATION__NAME,
    		
    		METHOD_DECLARATION__RETURN_TYPE,
    		
    		METHOD_DECLARATION__PARAMETERS,
    		
    		METHOD_DECLARATION__THROWN_EXCEPTIONS,
    		
    		METHOD_DECLARATION__TYPE_PARAMETERS,
    		
    		METHOD_DECLARATION__BINDING,
    		
    		ANNOTATION_TYPE_DECLARATION__MODIFIERS,
    		
    		ANNOTATION_TYPE_DECLARATION__JAVADOC,
    		
    		ANNOTATION_TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		ANNOTATION_TYPE_DECLARATION__NAME,
    		
    		ENUM_DECLARATION__MODIFIERS,
    		
    		ENUM_DECLARATION__JAVADOC,
    		
    		ENUM_DECLARATION__BODY_DECLARATIONS,
    		
    		ENUM_DECLARATION__NAME,
    		
    		ENUM_DECLARATION__SUPER_INTERFACE_TYPES,
    		
    		ENUM_DECLARATION__ENUM_CONSTANTS,
    		
    		TYPE_DECLARATION__MODIFIERS,
    		
    		TYPE_DECLARATION__JAVADOC,
    		
    		TYPE_DECLARATION__BODY_DECLARATIONS,
    		
    		TYPE_DECLARATION__NAME,
    		
    		TYPE_DECLARATION__SUPERCLASS_TYPE,
    		
    		TYPE_DECLARATION__SUPER_INTERFACE_TYPES,
    		
    		TYPE_DECLARATION__TYPE_PARAMETERS,
    		
    		BLOCK_COMMENT__ALTERNATE_ROOT,
    		
    		JAVADOC__ALTERNATE_ROOT,
    		
    		JAVADOC__TAGS,
    		
    		LINE_COMMENT__ALTERNATE_ROOT,
    		
    		ANNOTATION__TYPE_BINDING,
    		
    		ANNOTATION__TYPE_NAME,
    		
    		ARRAY_ACCESS__TYPE_BINDING,
    		
    		ARRAY_ACCESS__ARRAY,
    		
    		ARRAY_ACCESS__INDEX,
    		
    		ARRAY_CREATION__TYPE_BINDING,
    		
    		ARRAY_CREATION__DIMENSIONS,
    		
    		ARRAY_CREATION__INITIALIZER,
    		
    		ARRAY_CREATION__TYPE,
    		
    		ARRAY_INITIALIZER__TYPE_BINDING,
    		
    		ARRAY_INITIALIZER__EXPRESSIONS,
    		
    		ASSIGNMENT__TYPE_BINDING,
    		
    		ASSIGNMENT__LEFT_HAND_SIDE,
    		
    		ASSIGNMENT__RIGHT_HAND_SIDE,
    		
    		BOOLEAN_LITERAL__TYPE_BINDING,
    		
    		CAST_EXPRESSION__TYPE_BINDING,
    		
    		CAST_EXPRESSION__EXPRESSION,
    		
    		CAST_EXPRESSION__TYPE,
    		
    		CHARACTER_LITERAL__TYPE_BINDING,
    		
    		CLASS_INSTANCE_CREATION__TYPE_BINDING,
    		
    		CLASS_INSTANCE_CREATION__ARGUMENTS,
    		
    		CLASS_INSTANCE_CREATION__ANONYMOUS_CLASS_DECLARATION,
    		
    		CLASS_INSTANCE_CREATION__EXPRESSION,
    		
    		CLASS_INSTANCE_CREATION__TYPE,
    		
    		CLASS_INSTANCE_CREATION__TYPE_ARGUMENTS,
    		
    		CONDITIONAL_EXPRESSION__TYPE_BINDING,
    		
    		CONDITIONAL_EXPRESSION__ELSE_EXPRESSION,
    		
    		CONDITIONAL_EXPRESSION__EXPRESSION,
    		
    		CONDITIONAL_EXPRESSION__THEN_EXPRESSION,
    		
    		FIELD_ACCESS__TYPE_BINDING,
    		
    		FIELD_ACCESS__EXPRESSION,
    		
    		FIELD_ACCESS__NAME,
    		
    		INFIX_EXPRESSION__TYPE_BINDING,
    		
    		INFIX_EXPRESSION__EXTENDED_OPERANDS,
    		
    		INFIX_EXPRESSION__LEFT_OPERAND,
    		
    		INFIX_EXPRESSION__RIGHT_OPERAND,
    		
    		INSTANCEOF_EXPRESSION__TYPE_BINDING,
    		
    		INSTANCEOF_EXPRESSION__LEFT_OPERAND,
    		
    		INSTANCEOF_EXPRESSION__RIGHT_OPERAND,
    		
    		METHOD_INVOCATION__TYPE_BINDING,
    		
    		METHOD_INVOCATION__ARGUMENTS,
    		
    		METHOD_INVOCATION__EXPRESSION,
    		
    		METHOD_INVOCATION__NAME,
    		
    		METHOD_INVOCATION__TYPE_ARGUMENTS,
    		
    		METHOD_INVOCATION__METHOD_BINDING,
    		
    		NAME__TYPE_BINDING,
    		
    		NULL_LITERAL__TYPE_BINDING,
    		
    		NUMBER_LITERAL__TYPE_BINDING,
    		
    		PARENTHESIZED_EXPRESSION__TYPE_BINDING,
    		
    		PARENTHESIZED_EXPRESSION__EXPRESSION,
    		
    		POSTFIX_EXPRESSION__TYPE_BINDING,
    		
    		POSTFIX_EXPRESSION__OPERAND,
    		
    		PREFIX_EXPRESSION__TYPE_BINDING,
    		
    		PREFIX_EXPRESSION__OPERAND,
    		
    		STRING_LITERAL__TYPE_BINDING,
    		
    		SUPER_FIELD_ACCESS__TYPE_BINDING,
    		
    		SUPER_FIELD_ACCESS__NAME,
    		
    		SUPER_FIELD_ACCESS__QUALIFIER,
    		
    		SUPER_METHOD_INVOCATION__TYPE_BINDING,
    		
    		SUPER_METHOD_INVOCATION__ARGUMENTS,
    		
    		SUPER_METHOD_INVOCATION__NAME,
    		
    		SUPER_METHOD_INVOCATION__QUALIFIER,
    		
    		SUPER_METHOD_INVOCATION__TYPE_ARGUMENTS,
    		
    		THIS_EXPRESSION__TYPE_BINDING,
    		
    		THIS_EXPRESSION__QUALIFIER,
    		
    		TYPE_LITERAL__TYPE_BINDING,
    		
    		TYPE_LITERAL__TYPE,
    		
    		VARIABLE_DECLARATION_EXPRESSION__TYPE_BINDING,
    		
    		VARIABLE_DECLARATION_EXPRESSION__FRAGMENTS,
    		
    		VARIABLE_DECLARATION_EXPRESSION__MODIFIERS,
    		
    		VARIABLE_DECLARATION_EXPRESSION__TYPE,
    		
    		ASSERT_STATEMENT__EXPRESSION,
    		
    		ASSERT_STATEMENT__MESSAGE,
    		
    		BLOCK__STATEMENTS,
    		
    		BREAK_STATEMENT__LABEL,
    		
    		CONSTRUCTOR_INVOCATION__ARGUMENTS,
    		
    		CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS,
    		
    		CONTINUE_STATEMENT__LABEL,
    		
    		DO_STATEMENT__BODY,
    		
    		DO_STATEMENT__EXPRESSION,
    		
    		ENHANCED_FOR_STATEMENT__BODY,
    		
    		ENHANCED_FOR_STATEMENT__EXPRESSION,
    		
    		ENHANCED_FOR_STATEMENT__PARAMETER,
    		
    		EXPRESSION_STATEMENT__EXPRESSION,
    		
    		FOR_STATEMENT__BODY,
    		
    		FOR_STATEMENT__EXPRESSION,
    		
    		FOR_STATEMENT__INITIALIZERS,
    		
    		FOR_STATEMENT__UPDATERS,
    		
    		IF_STATEMENT__ELSE_STATEMENT,
    		
    		IF_STATEMENT__EXPRESSION,
    		
    		IF_STATEMENT__THEN_STATEMENT,
    		
    		LABELED_STATEMENT__BODY,
    		
    		LABELED_STATEMENT__LABEL,
    		
    		RETURN_STATEMENT__EXPRESSION,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__ARGUMENTS,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__EXPRESSION,
    		
    		SUPER_CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS,
    		
    		SWITCH_CASE__EXPRESSION,
    		
    		SWITCH_STATEMENT__EXPRESSION,
    		
    		SWITCH_STATEMENT__STATEMENTS,
    		
    		SYNCHRONIZED_STATEMENT__BODY,
    		
    		SYNCHRONIZED_STATEMENT__EXPRESSION,
    		
    		THROW_STATEMENT__EXPRESSION,
    		
    		TRY_STATEMENT__CATCH_CLAUSES,
    		
    		TRY_STATEMENT__BODY,
    		
    		TRY_STATEMENT__FINALLY,
    		
    		TYPE_DECLARATION_STATEMENT__DECLARATION,
    		
    		VARIABLE_DECLARATION_STATEMENT__FRAGMENTS,
    		
    		VARIABLE_DECLARATION_STATEMENT__MODIFIERS,
    		
    		VARIABLE_DECLARATION_STATEMENT__TYPE,
    		
    		WHILE_STATEMENT__BODY,
    		
    		WHILE_STATEMENT__EXPRESSION,
    		
    		ARRAY_TYPE__COMPONENT_TYPE,
    		
    		ARRAY_TYPE__ELEMENT_TYPE,
    		
    		PARAMETERIZED_TYPE__TYPE,
    		
    		PARAMETERIZED_TYPE__TYPE_ARGUMENTS,
    		
    		QUALIFIED_TYPE__NAME,
    		
    		QUALIFIED_TYPE__QUALIFIER,
    		
    		SIMPLE_TYPE__NAME,
    		
    		WILDCARD_TYPE__BOUND,
    		
    		SINGLE_VARIABLE_DECLARATION__INITIALIZER,
    		
    		SINGLE_VARIABLE_DECLARATION__NAME,
    		
    		SINGLE_VARIABLE_DECLARATION__TYPE,
    		
    		SINGLE_VARIABLE_DECLARATION__MODIFIERS,
    		
    		VARIABLE_DECLARATION_FRAGMENT__INITIALIZER,
    		
    		VARIABLE_DECLARATION_FRAGMENT__NAME,
    		
    		QUALIFIED_NAME__TYPE_BINDING,
    		
    		QUALIFIED_NAME__NAME,
    		
    		QUALIFIED_NAME__QUALIFIER,
    		
    		SIMPLE_NAME__TYPE_BINDING,
    		
    		MARKER_ANNOTATION__TYPE_BINDING,
    		
    		MARKER_ANNOTATION__TYPE_NAME,
    		
    		NORMAL_ANNOTATION__TYPE_BINDING,
    		
    		NORMAL_ANNOTATION__TYPE_NAME,
    		
    		NORMAL_ANNOTATION__VALUES,
    		
    		SINGLE_MEMBER_ANNOTATION__TYPE_BINDING,
    		
    		SINGLE_MEMBER_ANNOTATION__TYPE_NAME,
    		
    		SINGLE_MEMBER_ANNOTATION__VALUE,    		
} 
//Reltypes Class
