/**
 *
 * $Id$
 */
package reltypes;

import Core.CorePackage;

import DOM.DOMPackage;


import fr.inria.atlanmod.neo4emf.Point;

import java.util.HashMap;
import java.util.Map;

import org.neo4j.graphdb.RelationshipType;

/**
 * <!-- begin-user-doc -->
 * Neo4j <b>relationships mapping</b> for model persistence.
 * It provides hashmaps to map relationships to the appropriate feature ID.
 * <!-- end-user-doc -->
 * @generated
 */
public class ReltypesMappings {
	private static ReltypesMappings instance;
	
	
	/**
	 * 
	 * @generated
	 */
	 
	public static ReltypesMappings getInstance(){
		if (instance == null)
			return new ReltypesMappings ();
		else return instance;
		}
		
	/**
	 *getter of the Map
	 * @generated
	 */
		public Map<String,Map<Point,RelationshipType>> getMap(){
		return reference2relation;
	}
	
	/**
	 * constructor of Relationship type mappings
	 * @generated
	 */
		private final Map<String,Map<Point,RelationshipType>> reference2relation;
	
		private ReltypesMappings (){
			
			reference2relation= new HashMap<String,Map<Point,RelationshipType>>();		
		
			
		
					Map<Point,RelationshipType> mapCorePackage = new HashMap<Point,RelationshipType>();
				
			mapCorePackage.put(new Point(CorePackage.IJAVA_MODEL,CorePackage.IJAVA_MODEL__JAVA_PROJECTS),Reltypes.IJAVA_MODEL__JAVA_PROJECTS);
					
			mapCorePackage.put(new Point(CorePackage.IJAVA_MODEL,CorePackage.IJAVA_MODEL__EXTERNAL_PACKAGE_FRAGMENT_ROOTS),Reltypes.IJAVA_MODEL__EXTERNAL_PACKAGE_FRAGMENT_ROOTS);
					
			mapCorePackage.put(new Point(CorePackage.IJAVA_PROJECT,CorePackage.IJAVA_PROJECT__PACKAGE_FRAGMENT_ROOTS),Reltypes.IJAVA_PROJECT__PACKAGE_FRAGMENT_ROOTS);
					
			mapCorePackage.put(new Point(CorePackage.IJAVA_PROJECT,CorePackage.IJAVA_PROJECT__EXTERNAL_PACKAGE_FRAGMENT_ROOTS),Reltypes.IJAVA_PROJECT__EXTERNAL_PACKAGE_FRAGMENT_ROOTS);
					
			mapCorePackage.put(new Point(CorePackage.IJAVA_PROJECT,CorePackage.IJAVA_PROJECT__REQUIRED_PROJECTS),Reltypes.IJAVA_PROJECT__REQUIRED_PROJECTS);
					
			mapCorePackage.put(new Point(CorePackage.IPACKAGE_FRAGMENT_ROOT,CorePackage.IPACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS),Reltypes.IPACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS);
					
			mapCorePackage.put(new Point(CorePackage.BINARY_PACKAGE_FRAGMENT_ROOT,CorePackage.BINARY_PACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS),Reltypes.BINARY_PACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS);
					
			mapCorePackage.put(new Point(CorePackage.SOURCE_PACKAGE_FRAGMENT_ROOT,CorePackage.SOURCE_PACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS),Reltypes.SOURCE_PACKAGE_FRAGMENT_ROOT__PACKAGE_FRAGMENTS);
					
			mapCorePackage.put(new Point(CorePackage.IPACKAGE_FRAGMENT,CorePackage.IPACKAGE_FRAGMENT__PACKAGE_FRAGMENT_ROOT),Reltypes.IPACKAGE_FRAGMENT__PACKAGE_FRAGMENT_ROOT);
					
			mapCorePackage.put(new Point(CorePackage.IPACKAGE_FRAGMENT,CorePackage.IPACKAGE_FRAGMENT__CLASS_FILES),Reltypes.IPACKAGE_FRAGMENT__CLASS_FILES);
					
			mapCorePackage.put(new Point(CorePackage.IPACKAGE_FRAGMENT,CorePackage.IPACKAGE_FRAGMENT__COMPILATION_UNITS),Reltypes.IPACKAGE_FRAGMENT__COMPILATION_UNITS);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE_ROOT,CorePackage.ITYPE_ROOT__SOURCE_RANGE),Reltypes.ITYPE_ROOT__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ICOMPILATION_UNIT,CorePackage.ICOMPILATION_UNIT__SOURCE_RANGE),Reltypes.ICOMPILATION_UNIT__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ICOMPILATION_UNIT,CorePackage.ICOMPILATION_UNIT__ALL_TYPE),Reltypes.ICOMPILATION_UNIT__ALL_TYPE);
					
			mapCorePackage.put(new Point(CorePackage.ICOMPILATION_UNIT,CorePackage.ICOMPILATION_UNIT__IMPORTS),Reltypes.ICOMPILATION_UNIT__IMPORTS);
					
			mapCorePackage.put(new Point(CorePackage.ICOMPILATION_UNIT,CorePackage.ICOMPILATION_UNIT__TYPES),Reltypes.ICOMPILATION_UNIT__TYPES);
					
			mapCorePackage.put(new Point(CorePackage.ICOMPILATION_UNIT,CorePackage.ICOMPILATION_UNIT__PRIMARY),Reltypes.ICOMPILATION_UNIT__PRIMARY);
					
			mapCorePackage.put(new Point(CorePackage.ICOMPILATION_UNIT,CorePackage.ICOMPILATION_UNIT__AST),Reltypes.ICOMPILATION_UNIT__AST);
					
			mapCorePackage.put(new Point(CorePackage.ICLASS_FILE,CorePackage.ICLASS_FILE__SOURCE_RANGE),Reltypes.ICLASS_FILE__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ICLASS_FILE,CorePackage.ICLASS_FILE__TYPE),Reltypes.ICLASS_FILE__TYPE);
					
			mapCorePackage.put(new Point(CorePackage.ISOURCE_REFERENCE,CorePackage.ISOURCE_REFERENCE__SOURCE_RANGE),Reltypes.ISOURCE_REFERENCE__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IIMPORT_DECLARATION,CorePackage.IIMPORT_DECLARATION__SOURCE_RANGE),Reltypes.IIMPORT_DECLARATION__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMEMBER,CorePackage.IMEMBER__SOURCE_RANGE),Reltypes.IMEMBER__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMEMBER,CorePackage.IMEMBER__JAVADOC_RANGE),Reltypes.IMEMBER__JAVADOC_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMEMBER,CorePackage.IMEMBER__NAME_RANGE),Reltypes.IMEMBER__NAME_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__SOURCE_RANGE),Reltypes.ITYPE__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__JAVADOC_RANGE),Reltypes.ITYPE__JAVADOC_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__NAME_RANGE),Reltypes.ITYPE__NAME_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__INITIALIZERS),Reltypes.ITYPE__INITIALIZERS);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__FIELDS),Reltypes.ITYPE__FIELDS);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__METHODS),Reltypes.ITYPE__METHODS);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__TYPES),Reltypes.ITYPE__TYPES);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE,CorePackage.ITYPE__TYPE_PARAMETERS),Reltypes.ITYPE__TYPE_PARAMETERS);
					
			mapCorePackage.put(new Point(CorePackage.ITYPE_PARAMETER,CorePackage.ITYPE_PARAMETER__SOURCE_RANGE),Reltypes.ITYPE_PARAMETER__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IINITIALIZER,CorePackage.IINITIALIZER__SOURCE_RANGE),Reltypes.IINITIALIZER__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IINITIALIZER,CorePackage.IINITIALIZER__JAVADOC_RANGE),Reltypes.IINITIALIZER__JAVADOC_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IINITIALIZER,CorePackage.IINITIALIZER__NAME_RANGE),Reltypes.IINITIALIZER__NAME_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IFIELD,CorePackage.IFIELD__SOURCE_RANGE),Reltypes.IFIELD__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IFIELD,CorePackage.IFIELD__JAVADOC_RANGE),Reltypes.IFIELD__JAVADOC_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IFIELD,CorePackage.IFIELD__NAME_RANGE),Reltypes.IFIELD__NAME_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMETHOD,CorePackage.IMETHOD__SOURCE_RANGE),Reltypes.IMETHOD__SOURCE_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMETHOD,CorePackage.IMETHOD__JAVADOC_RANGE),Reltypes.IMETHOD__JAVADOC_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMETHOD,CorePackage.IMETHOD__NAME_RANGE),Reltypes.IMETHOD__NAME_RANGE);
					
			mapCorePackage.put(new Point(CorePackage.IMETHOD,CorePackage.IMETHOD__PARAMETERS),Reltypes.IMETHOD__PARAMETERS);
					
			reference2relation.put(CorePackage.eNS_URI,mapCorePackage);
		
		
			
		
					Map<Point,RelationshipType> mapDOMPackage = new HashMap<Point,RelationshipType>();
				
			mapDOMPackage.put(new Point(DOMPackage.AST,DOMPackage.AST__COMPILATION_UNITS),Reltypes.AST__COMPILATION_UNITS);
					
			mapDOMPackage.put(new Point(DOMPackage.ANONYMOUS_CLASS_DECLARATION,DOMPackage.ANONYMOUS_CLASS_DECLARATION__BODY_DECLARATIONS),Reltypes.ANONYMOUS_CLASS_DECLARATION__BODY_DECLARATIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.BODY_DECLARATION,DOMPackage.BODY_DECLARATION__MODIFIERS),Reltypes.BODY_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.BODY_DECLARATION,DOMPackage.BODY_DECLARATION__JAVADOC),Reltypes.BODY_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.CATCH_CLAUSE,DOMPackage.CATCH_CLAUSE__BODY),Reltypes.CATCH_CLAUSE__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.CATCH_CLAUSE,DOMPackage.CATCH_CLAUSE__EXCEPTION),Reltypes.CATCH_CLAUSE__EXCEPTION);
					
			mapDOMPackage.put(new Point(DOMPackage.COMMENT,DOMPackage.COMMENT__ALTERNATE_ROOT),Reltypes.COMMENT__ALTERNATE_ROOT);
					
			mapDOMPackage.put(new Point(DOMPackage.COMPILATION_UNIT,DOMPackage.COMPILATION_UNIT__COMMENTS),Reltypes.COMPILATION_UNIT__COMMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.COMPILATION_UNIT,DOMPackage.COMPILATION_UNIT__PACKAGE),Reltypes.COMPILATION_UNIT__PACKAGE);
					
			mapDOMPackage.put(new Point(DOMPackage.COMPILATION_UNIT,DOMPackage.COMPILATION_UNIT__IMPORTS),Reltypes.COMPILATION_UNIT__IMPORTS);
					
			mapDOMPackage.put(new Point(DOMPackage.COMPILATION_UNIT,DOMPackage.COMPILATION_UNIT__TYPES),Reltypes.COMPILATION_UNIT__TYPES);
					
			mapDOMPackage.put(new Point(DOMPackage.EXPRESSION,DOMPackage.EXPRESSION__TYPE_BINDING),Reltypes.EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.IMPORT_DECLARATION,DOMPackage.IMPORT_DECLARATION__NAME),Reltypes.IMPORT_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.MEMBER_REF,DOMPackage.MEMBER_REF__NAME),Reltypes.MEMBER_REF__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.MEMBER_REF,DOMPackage.MEMBER_REF__QUALIFIER),Reltypes.MEMBER_REF__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.MEMBER_VALUE_PAIR,DOMPackage.MEMBER_VALUE_PAIR__NAME),Reltypes.MEMBER_VALUE_PAIR__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.MEMBER_VALUE_PAIR,DOMPackage.MEMBER_VALUE_PAIR__VALUE),Reltypes.MEMBER_VALUE_PAIR__VALUE);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_REF,DOMPackage.METHOD_REF__NAME),Reltypes.METHOD_REF__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_REF,DOMPackage.METHOD_REF__QUALIFIER),Reltypes.METHOD_REF__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_REF,DOMPackage.METHOD_REF__PARAMETERS),Reltypes.METHOD_REF__PARAMETERS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_REF_PARAMETER,DOMPackage.METHOD_REF_PARAMETER__NAME),Reltypes.METHOD_REF_PARAMETER__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_REF_PARAMETER,DOMPackage.METHOD_REF_PARAMETER__TYPE),Reltypes.METHOD_REF_PARAMETER__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.PACKAGE_DECLARATION,DOMPackage.PACKAGE_DECLARATION__ANNOTATIONS),Reltypes.PACKAGE_DECLARATION__ANNOTATIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.PACKAGE_DECLARATION,DOMPackage.PACKAGE_DECLARATION__JAVADOC),Reltypes.PACKAGE_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.PACKAGE_DECLARATION,DOMPackage.PACKAGE_DECLARATION__NAME),Reltypes.PACKAGE_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.PACKAGE_DECLARATION,DOMPackage.PACKAGE_DECLARATION__BINDING),Reltypes.PACKAGE_DECLARATION__BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.TAG_ELEMENT,DOMPackage.TAG_ELEMENT__FRAGMENTS),Reltypes.TAG_ELEMENT__FRAGMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_PARAMETER,DOMPackage.TYPE_PARAMETER__NAME),Reltypes.TYPE_PARAMETER__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_PARAMETER,DOMPackage.TYPE_PARAMETER__TYPE_BOUNDS),Reltypes.TYPE_PARAMETER__TYPE_BOUNDS);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION,DOMPackage.VARIABLE_DECLARATION__INITIALIZER),Reltypes.VARIABLE_DECLARATION__INITIALIZER);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION,DOMPackage.VARIABLE_DECLARATION__NAME),Reltypes.VARIABLE_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.ABSTRACT_TYPE_DECLARATION,DOMPackage.ABSTRACT_TYPE_DECLARATION__MODIFIERS),Reltypes.ABSTRACT_TYPE_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.ABSTRACT_TYPE_DECLARATION,DOMPackage.ABSTRACT_TYPE_DECLARATION__JAVADOC),Reltypes.ABSTRACT_TYPE_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.ABSTRACT_TYPE_DECLARATION,DOMPackage.ABSTRACT_TYPE_DECLARATION__BODY_DECLARATIONS),Reltypes.ABSTRACT_TYPE_DECLARATION__BODY_DECLARATIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.ABSTRACT_TYPE_DECLARATION,DOMPackage.ABSTRACT_TYPE_DECLARATION__NAME),Reltypes.ABSTRACT_TYPE_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION,DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION__MODIFIERS),Reltypes.ANNOTATION_TYPE_MEMBER_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION,DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION__JAVADOC),Reltypes.ANNOTATION_TYPE_MEMBER_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION,DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION__DEFAULT),Reltypes.ANNOTATION_TYPE_MEMBER_DECLARATION__DEFAULT);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION,DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION__NAME),Reltypes.ANNOTATION_TYPE_MEMBER_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION,DOMPackage.ANNOTATION_TYPE_MEMBER_DECLARATION__TYPE),Reltypes.ANNOTATION_TYPE_MEMBER_DECLARATION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_CONSTANT_DECLARATION,DOMPackage.ENUM_CONSTANT_DECLARATION__MODIFIERS),Reltypes.ENUM_CONSTANT_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_CONSTANT_DECLARATION,DOMPackage.ENUM_CONSTANT_DECLARATION__JAVADOC),Reltypes.ENUM_CONSTANT_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_CONSTANT_DECLARATION,DOMPackage.ENUM_CONSTANT_DECLARATION__ARGUMENTS),Reltypes.ENUM_CONSTANT_DECLARATION__ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_CONSTANT_DECLARATION,DOMPackage.ENUM_CONSTANT_DECLARATION__ANONYMOUS_CLASS_DECLARATION),Reltypes.ENUM_CONSTANT_DECLARATION__ANONYMOUS_CLASS_DECLARATION);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_CONSTANT_DECLARATION,DOMPackage.ENUM_CONSTANT_DECLARATION__NAME),Reltypes.ENUM_CONSTANT_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_DECLARATION,DOMPackage.FIELD_DECLARATION__MODIFIERS),Reltypes.FIELD_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_DECLARATION,DOMPackage.FIELD_DECLARATION__JAVADOC),Reltypes.FIELD_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_DECLARATION,DOMPackage.FIELD_DECLARATION__FRAGMENTS),Reltypes.FIELD_DECLARATION__FRAGMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_DECLARATION,DOMPackage.FIELD_DECLARATION__TYPE),Reltypes.FIELD_DECLARATION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.INITIALIZER,DOMPackage.INITIALIZER__MODIFIERS),Reltypes.INITIALIZER__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.INITIALIZER,DOMPackage.INITIALIZER__JAVADOC),Reltypes.INITIALIZER__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.INITIALIZER,DOMPackage.INITIALIZER__BODY),Reltypes.INITIALIZER__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__MODIFIERS),Reltypes.METHOD_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__JAVADOC),Reltypes.METHOD_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__BODY),Reltypes.METHOD_DECLARATION__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__NAME),Reltypes.METHOD_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__RETURN_TYPE),Reltypes.METHOD_DECLARATION__RETURN_TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__PARAMETERS),Reltypes.METHOD_DECLARATION__PARAMETERS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__THROWN_EXCEPTIONS),Reltypes.METHOD_DECLARATION__THROWN_EXCEPTIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__TYPE_PARAMETERS),Reltypes.METHOD_DECLARATION__TYPE_PARAMETERS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_DECLARATION,DOMPackage.METHOD_DECLARATION__BINDING),Reltypes.METHOD_DECLARATION__BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_DECLARATION,DOMPackage.ANNOTATION_TYPE_DECLARATION__MODIFIERS),Reltypes.ANNOTATION_TYPE_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_DECLARATION,DOMPackage.ANNOTATION_TYPE_DECLARATION__JAVADOC),Reltypes.ANNOTATION_TYPE_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_DECLARATION,DOMPackage.ANNOTATION_TYPE_DECLARATION__BODY_DECLARATIONS),Reltypes.ANNOTATION_TYPE_DECLARATION__BODY_DECLARATIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION_TYPE_DECLARATION,DOMPackage.ANNOTATION_TYPE_DECLARATION__NAME),Reltypes.ANNOTATION_TYPE_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_DECLARATION,DOMPackage.ENUM_DECLARATION__MODIFIERS),Reltypes.ENUM_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_DECLARATION,DOMPackage.ENUM_DECLARATION__JAVADOC),Reltypes.ENUM_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_DECLARATION,DOMPackage.ENUM_DECLARATION__BODY_DECLARATIONS),Reltypes.ENUM_DECLARATION__BODY_DECLARATIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_DECLARATION,DOMPackage.ENUM_DECLARATION__NAME),Reltypes.ENUM_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_DECLARATION,DOMPackage.ENUM_DECLARATION__SUPER_INTERFACE_TYPES),Reltypes.ENUM_DECLARATION__SUPER_INTERFACE_TYPES);
					
			mapDOMPackage.put(new Point(DOMPackage.ENUM_DECLARATION,DOMPackage.ENUM_DECLARATION__ENUM_CONSTANTS),Reltypes.ENUM_DECLARATION__ENUM_CONSTANTS);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__MODIFIERS),Reltypes.TYPE_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__JAVADOC),Reltypes.TYPE_DECLARATION__JAVADOC);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__BODY_DECLARATIONS),Reltypes.TYPE_DECLARATION__BODY_DECLARATIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__NAME),Reltypes.TYPE_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__SUPERCLASS_TYPE),Reltypes.TYPE_DECLARATION__SUPERCLASS_TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__SUPER_INTERFACE_TYPES),Reltypes.TYPE_DECLARATION__SUPER_INTERFACE_TYPES);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION,DOMPackage.TYPE_DECLARATION__TYPE_PARAMETERS),Reltypes.TYPE_DECLARATION__TYPE_PARAMETERS);
					
			mapDOMPackage.put(new Point(DOMPackage.BLOCK_COMMENT,DOMPackage.BLOCK_COMMENT__ALTERNATE_ROOT),Reltypes.BLOCK_COMMENT__ALTERNATE_ROOT);
					
			mapDOMPackage.put(new Point(DOMPackage.JAVADOC,DOMPackage.JAVADOC__ALTERNATE_ROOT),Reltypes.JAVADOC__ALTERNATE_ROOT);
					
			mapDOMPackage.put(new Point(DOMPackage.JAVADOC,DOMPackage.JAVADOC__TAGS),Reltypes.JAVADOC__TAGS);
					
			mapDOMPackage.put(new Point(DOMPackage.LINE_COMMENT,DOMPackage.LINE_COMMENT__ALTERNATE_ROOT),Reltypes.LINE_COMMENT__ALTERNATE_ROOT);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION,DOMPackage.ANNOTATION__TYPE_BINDING),Reltypes.ANNOTATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.ANNOTATION,DOMPackage.ANNOTATION__TYPE_NAME),Reltypes.ANNOTATION__TYPE_NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_ACCESS,DOMPackage.ARRAY_ACCESS__TYPE_BINDING),Reltypes.ARRAY_ACCESS__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_ACCESS,DOMPackage.ARRAY_ACCESS__ARRAY),Reltypes.ARRAY_ACCESS__ARRAY);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_ACCESS,DOMPackage.ARRAY_ACCESS__INDEX),Reltypes.ARRAY_ACCESS__INDEX);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_CREATION,DOMPackage.ARRAY_CREATION__TYPE_BINDING),Reltypes.ARRAY_CREATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_CREATION,DOMPackage.ARRAY_CREATION__DIMENSIONS),Reltypes.ARRAY_CREATION__DIMENSIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_CREATION,DOMPackage.ARRAY_CREATION__INITIALIZER),Reltypes.ARRAY_CREATION__INITIALIZER);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_CREATION,DOMPackage.ARRAY_CREATION__TYPE),Reltypes.ARRAY_CREATION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_INITIALIZER,DOMPackage.ARRAY_INITIALIZER__TYPE_BINDING),Reltypes.ARRAY_INITIALIZER__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_INITIALIZER,DOMPackage.ARRAY_INITIALIZER__EXPRESSIONS),Reltypes.ARRAY_INITIALIZER__EXPRESSIONS);
					
			mapDOMPackage.put(new Point(DOMPackage.ASSIGNMENT,DOMPackage.ASSIGNMENT__TYPE_BINDING),Reltypes.ASSIGNMENT__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.ASSIGNMENT,DOMPackage.ASSIGNMENT__LEFT_HAND_SIDE),Reltypes.ASSIGNMENT__LEFT_HAND_SIDE);
					
			mapDOMPackage.put(new Point(DOMPackage.ASSIGNMENT,DOMPackage.ASSIGNMENT__RIGHT_HAND_SIDE),Reltypes.ASSIGNMENT__RIGHT_HAND_SIDE);
					
			mapDOMPackage.put(new Point(DOMPackage.BOOLEAN_LITERAL,DOMPackage.BOOLEAN_LITERAL__TYPE_BINDING),Reltypes.BOOLEAN_LITERAL__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.CAST_EXPRESSION,DOMPackage.CAST_EXPRESSION__TYPE_BINDING),Reltypes.CAST_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.CAST_EXPRESSION,DOMPackage.CAST_EXPRESSION__EXPRESSION),Reltypes.CAST_EXPRESSION__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.CAST_EXPRESSION,DOMPackage.CAST_EXPRESSION__TYPE),Reltypes.CAST_EXPRESSION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.CHARACTER_LITERAL,DOMPackage.CHARACTER_LITERAL__TYPE_BINDING),Reltypes.CHARACTER_LITERAL__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.CLASS_INSTANCE_CREATION,DOMPackage.CLASS_INSTANCE_CREATION__TYPE_BINDING),Reltypes.CLASS_INSTANCE_CREATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.CLASS_INSTANCE_CREATION,DOMPackage.CLASS_INSTANCE_CREATION__ARGUMENTS),Reltypes.CLASS_INSTANCE_CREATION__ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.CLASS_INSTANCE_CREATION,DOMPackage.CLASS_INSTANCE_CREATION__ANONYMOUS_CLASS_DECLARATION),Reltypes.CLASS_INSTANCE_CREATION__ANONYMOUS_CLASS_DECLARATION);
					
			mapDOMPackage.put(new Point(DOMPackage.CLASS_INSTANCE_CREATION,DOMPackage.CLASS_INSTANCE_CREATION__EXPRESSION),Reltypes.CLASS_INSTANCE_CREATION__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.CLASS_INSTANCE_CREATION,DOMPackage.CLASS_INSTANCE_CREATION__TYPE),Reltypes.CLASS_INSTANCE_CREATION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.CLASS_INSTANCE_CREATION,DOMPackage.CLASS_INSTANCE_CREATION__TYPE_ARGUMENTS),Reltypes.CLASS_INSTANCE_CREATION__TYPE_ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.CONDITIONAL_EXPRESSION,DOMPackage.CONDITIONAL_EXPRESSION__TYPE_BINDING),Reltypes.CONDITIONAL_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.CONDITIONAL_EXPRESSION,DOMPackage.CONDITIONAL_EXPRESSION__ELSE_EXPRESSION),Reltypes.CONDITIONAL_EXPRESSION__ELSE_EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.CONDITIONAL_EXPRESSION,DOMPackage.CONDITIONAL_EXPRESSION__EXPRESSION),Reltypes.CONDITIONAL_EXPRESSION__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.CONDITIONAL_EXPRESSION,DOMPackage.CONDITIONAL_EXPRESSION__THEN_EXPRESSION),Reltypes.CONDITIONAL_EXPRESSION__THEN_EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_ACCESS,DOMPackage.FIELD_ACCESS__TYPE_BINDING),Reltypes.FIELD_ACCESS__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_ACCESS,DOMPackage.FIELD_ACCESS__EXPRESSION),Reltypes.FIELD_ACCESS__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.FIELD_ACCESS,DOMPackage.FIELD_ACCESS__NAME),Reltypes.FIELD_ACCESS__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.INFIX_EXPRESSION,DOMPackage.INFIX_EXPRESSION__TYPE_BINDING),Reltypes.INFIX_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.INFIX_EXPRESSION,DOMPackage.INFIX_EXPRESSION__EXTENDED_OPERANDS),Reltypes.INFIX_EXPRESSION__EXTENDED_OPERANDS);
					
			mapDOMPackage.put(new Point(DOMPackage.INFIX_EXPRESSION,DOMPackage.INFIX_EXPRESSION__LEFT_OPERAND),Reltypes.INFIX_EXPRESSION__LEFT_OPERAND);
					
			mapDOMPackage.put(new Point(DOMPackage.INFIX_EXPRESSION,DOMPackage.INFIX_EXPRESSION__RIGHT_OPERAND),Reltypes.INFIX_EXPRESSION__RIGHT_OPERAND);
					
			mapDOMPackage.put(new Point(DOMPackage.INSTANCEOF_EXPRESSION,DOMPackage.INSTANCEOF_EXPRESSION__TYPE_BINDING),Reltypes.INSTANCEOF_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.INSTANCEOF_EXPRESSION,DOMPackage.INSTANCEOF_EXPRESSION__LEFT_OPERAND),Reltypes.INSTANCEOF_EXPRESSION__LEFT_OPERAND);
					
			mapDOMPackage.put(new Point(DOMPackage.INSTANCEOF_EXPRESSION,DOMPackage.INSTANCEOF_EXPRESSION__RIGHT_OPERAND),Reltypes.INSTANCEOF_EXPRESSION__RIGHT_OPERAND);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_INVOCATION,DOMPackage.METHOD_INVOCATION__TYPE_BINDING),Reltypes.METHOD_INVOCATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_INVOCATION,DOMPackage.METHOD_INVOCATION__ARGUMENTS),Reltypes.METHOD_INVOCATION__ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_INVOCATION,DOMPackage.METHOD_INVOCATION__EXPRESSION),Reltypes.METHOD_INVOCATION__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_INVOCATION,DOMPackage.METHOD_INVOCATION__NAME),Reltypes.METHOD_INVOCATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_INVOCATION,DOMPackage.METHOD_INVOCATION__TYPE_ARGUMENTS),Reltypes.METHOD_INVOCATION__TYPE_ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.METHOD_INVOCATION,DOMPackage.METHOD_INVOCATION__METHOD_BINDING),Reltypes.METHOD_INVOCATION__METHOD_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.NAME,DOMPackage.NAME__TYPE_BINDING),Reltypes.NAME__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.NULL_LITERAL,DOMPackage.NULL_LITERAL__TYPE_BINDING),Reltypes.NULL_LITERAL__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.NUMBER_LITERAL,DOMPackage.NUMBER_LITERAL__TYPE_BINDING),Reltypes.NUMBER_LITERAL__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.PARENTHESIZED_EXPRESSION,DOMPackage.PARENTHESIZED_EXPRESSION__TYPE_BINDING),Reltypes.PARENTHESIZED_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.PARENTHESIZED_EXPRESSION,DOMPackage.PARENTHESIZED_EXPRESSION__EXPRESSION),Reltypes.PARENTHESIZED_EXPRESSION__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.POSTFIX_EXPRESSION,DOMPackage.POSTFIX_EXPRESSION__TYPE_BINDING),Reltypes.POSTFIX_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.POSTFIX_EXPRESSION,DOMPackage.POSTFIX_EXPRESSION__OPERAND),Reltypes.POSTFIX_EXPRESSION__OPERAND);
					
			mapDOMPackage.put(new Point(DOMPackage.PREFIX_EXPRESSION,DOMPackage.PREFIX_EXPRESSION__TYPE_BINDING),Reltypes.PREFIX_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.PREFIX_EXPRESSION,DOMPackage.PREFIX_EXPRESSION__OPERAND),Reltypes.PREFIX_EXPRESSION__OPERAND);
					
			mapDOMPackage.put(new Point(DOMPackage.STRING_LITERAL,DOMPackage.STRING_LITERAL__TYPE_BINDING),Reltypes.STRING_LITERAL__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_FIELD_ACCESS,DOMPackage.SUPER_FIELD_ACCESS__TYPE_BINDING),Reltypes.SUPER_FIELD_ACCESS__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_FIELD_ACCESS,DOMPackage.SUPER_FIELD_ACCESS__NAME),Reltypes.SUPER_FIELD_ACCESS__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_FIELD_ACCESS,DOMPackage.SUPER_FIELD_ACCESS__QUALIFIER),Reltypes.SUPER_FIELD_ACCESS__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_METHOD_INVOCATION,DOMPackage.SUPER_METHOD_INVOCATION__TYPE_BINDING),Reltypes.SUPER_METHOD_INVOCATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_METHOD_INVOCATION,DOMPackage.SUPER_METHOD_INVOCATION__ARGUMENTS),Reltypes.SUPER_METHOD_INVOCATION__ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_METHOD_INVOCATION,DOMPackage.SUPER_METHOD_INVOCATION__NAME),Reltypes.SUPER_METHOD_INVOCATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_METHOD_INVOCATION,DOMPackage.SUPER_METHOD_INVOCATION__QUALIFIER),Reltypes.SUPER_METHOD_INVOCATION__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_METHOD_INVOCATION,DOMPackage.SUPER_METHOD_INVOCATION__TYPE_ARGUMENTS),Reltypes.SUPER_METHOD_INVOCATION__TYPE_ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.THIS_EXPRESSION,DOMPackage.THIS_EXPRESSION__TYPE_BINDING),Reltypes.THIS_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.THIS_EXPRESSION,DOMPackage.THIS_EXPRESSION__QUALIFIER),Reltypes.THIS_EXPRESSION__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_LITERAL,DOMPackage.TYPE_LITERAL__TYPE_BINDING),Reltypes.TYPE_LITERAL__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_LITERAL,DOMPackage.TYPE_LITERAL__TYPE),Reltypes.TYPE_LITERAL__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_EXPRESSION,DOMPackage.VARIABLE_DECLARATION_EXPRESSION__TYPE_BINDING),Reltypes.VARIABLE_DECLARATION_EXPRESSION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_EXPRESSION,DOMPackage.VARIABLE_DECLARATION_EXPRESSION__FRAGMENTS),Reltypes.VARIABLE_DECLARATION_EXPRESSION__FRAGMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_EXPRESSION,DOMPackage.VARIABLE_DECLARATION_EXPRESSION__MODIFIERS),Reltypes.VARIABLE_DECLARATION_EXPRESSION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_EXPRESSION,DOMPackage.VARIABLE_DECLARATION_EXPRESSION__TYPE),Reltypes.VARIABLE_DECLARATION_EXPRESSION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.ASSERT_STATEMENT,DOMPackage.ASSERT_STATEMENT__EXPRESSION),Reltypes.ASSERT_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.ASSERT_STATEMENT,DOMPackage.ASSERT_STATEMENT__MESSAGE),Reltypes.ASSERT_STATEMENT__MESSAGE);
					
			mapDOMPackage.put(new Point(DOMPackage.BLOCK,DOMPackage.BLOCK__STATEMENTS),Reltypes.BLOCK__STATEMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.BREAK_STATEMENT,DOMPackage.BREAK_STATEMENT__LABEL),Reltypes.BREAK_STATEMENT__LABEL);
					
			mapDOMPackage.put(new Point(DOMPackage.CONSTRUCTOR_INVOCATION,DOMPackage.CONSTRUCTOR_INVOCATION__ARGUMENTS),Reltypes.CONSTRUCTOR_INVOCATION__ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.CONSTRUCTOR_INVOCATION,DOMPackage.CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS),Reltypes.CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.CONTINUE_STATEMENT,DOMPackage.CONTINUE_STATEMENT__LABEL),Reltypes.CONTINUE_STATEMENT__LABEL);
					
			mapDOMPackage.put(new Point(DOMPackage.DO_STATEMENT,DOMPackage.DO_STATEMENT__BODY),Reltypes.DO_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.DO_STATEMENT,DOMPackage.DO_STATEMENT__EXPRESSION),Reltypes.DO_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.ENHANCED_FOR_STATEMENT,DOMPackage.ENHANCED_FOR_STATEMENT__BODY),Reltypes.ENHANCED_FOR_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.ENHANCED_FOR_STATEMENT,DOMPackage.ENHANCED_FOR_STATEMENT__EXPRESSION),Reltypes.ENHANCED_FOR_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.ENHANCED_FOR_STATEMENT,DOMPackage.ENHANCED_FOR_STATEMENT__PARAMETER),Reltypes.ENHANCED_FOR_STATEMENT__PARAMETER);
					
			mapDOMPackage.put(new Point(DOMPackage.EXPRESSION_STATEMENT,DOMPackage.EXPRESSION_STATEMENT__EXPRESSION),Reltypes.EXPRESSION_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.FOR_STATEMENT,DOMPackage.FOR_STATEMENT__BODY),Reltypes.FOR_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.FOR_STATEMENT,DOMPackage.FOR_STATEMENT__EXPRESSION),Reltypes.FOR_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.FOR_STATEMENT,DOMPackage.FOR_STATEMENT__INITIALIZERS),Reltypes.FOR_STATEMENT__INITIALIZERS);
					
			mapDOMPackage.put(new Point(DOMPackage.FOR_STATEMENT,DOMPackage.FOR_STATEMENT__UPDATERS),Reltypes.FOR_STATEMENT__UPDATERS);
					
			mapDOMPackage.put(new Point(DOMPackage.IF_STATEMENT,DOMPackage.IF_STATEMENT__ELSE_STATEMENT),Reltypes.IF_STATEMENT__ELSE_STATEMENT);
					
			mapDOMPackage.put(new Point(DOMPackage.IF_STATEMENT,DOMPackage.IF_STATEMENT__EXPRESSION),Reltypes.IF_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.IF_STATEMENT,DOMPackage.IF_STATEMENT__THEN_STATEMENT),Reltypes.IF_STATEMENT__THEN_STATEMENT);
					
			mapDOMPackage.put(new Point(DOMPackage.LABELED_STATEMENT,DOMPackage.LABELED_STATEMENT__BODY),Reltypes.LABELED_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.LABELED_STATEMENT,DOMPackage.LABELED_STATEMENT__LABEL),Reltypes.LABELED_STATEMENT__LABEL);
					
			mapDOMPackage.put(new Point(DOMPackage.RETURN_STATEMENT,DOMPackage.RETURN_STATEMENT__EXPRESSION),Reltypes.RETURN_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_CONSTRUCTOR_INVOCATION,DOMPackage.SUPER_CONSTRUCTOR_INVOCATION__ARGUMENTS),Reltypes.SUPER_CONSTRUCTOR_INVOCATION__ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_CONSTRUCTOR_INVOCATION,DOMPackage.SUPER_CONSTRUCTOR_INVOCATION__EXPRESSION),Reltypes.SUPER_CONSTRUCTOR_INVOCATION__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.SUPER_CONSTRUCTOR_INVOCATION,DOMPackage.SUPER_CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS),Reltypes.SUPER_CONSTRUCTOR_INVOCATION__TYPE_ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.SWITCH_CASE,DOMPackage.SWITCH_CASE__EXPRESSION),Reltypes.SWITCH_CASE__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.SWITCH_STATEMENT,DOMPackage.SWITCH_STATEMENT__EXPRESSION),Reltypes.SWITCH_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.SWITCH_STATEMENT,DOMPackage.SWITCH_STATEMENT__STATEMENTS),Reltypes.SWITCH_STATEMENT__STATEMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.SYNCHRONIZED_STATEMENT,DOMPackage.SYNCHRONIZED_STATEMENT__BODY),Reltypes.SYNCHRONIZED_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.SYNCHRONIZED_STATEMENT,DOMPackage.SYNCHRONIZED_STATEMENT__EXPRESSION),Reltypes.SYNCHRONIZED_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.THROW_STATEMENT,DOMPackage.THROW_STATEMENT__EXPRESSION),Reltypes.THROW_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.TRY_STATEMENT,DOMPackage.TRY_STATEMENT__CATCH_CLAUSES),Reltypes.TRY_STATEMENT__CATCH_CLAUSES);
					
			mapDOMPackage.put(new Point(DOMPackage.TRY_STATEMENT,DOMPackage.TRY_STATEMENT__BODY),Reltypes.TRY_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.TRY_STATEMENT,DOMPackage.TRY_STATEMENT__FINALLY),Reltypes.TRY_STATEMENT__FINALLY);
					
			mapDOMPackage.put(new Point(DOMPackage.TYPE_DECLARATION_STATEMENT,DOMPackage.TYPE_DECLARATION_STATEMENT__DECLARATION),Reltypes.TYPE_DECLARATION_STATEMENT__DECLARATION);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_STATEMENT,DOMPackage.VARIABLE_DECLARATION_STATEMENT__FRAGMENTS),Reltypes.VARIABLE_DECLARATION_STATEMENT__FRAGMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_STATEMENT,DOMPackage.VARIABLE_DECLARATION_STATEMENT__MODIFIERS),Reltypes.VARIABLE_DECLARATION_STATEMENT__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_STATEMENT,DOMPackage.VARIABLE_DECLARATION_STATEMENT__TYPE),Reltypes.VARIABLE_DECLARATION_STATEMENT__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.WHILE_STATEMENT,DOMPackage.WHILE_STATEMENT__BODY),Reltypes.WHILE_STATEMENT__BODY);
					
			mapDOMPackage.put(new Point(DOMPackage.WHILE_STATEMENT,DOMPackage.WHILE_STATEMENT__EXPRESSION),Reltypes.WHILE_STATEMENT__EXPRESSION);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_TYPE,DOMPackage.ARRAY_TYPE__COMPONENT_TYPE),Reltypes.ARRAY_TYPE__COMPONENT_TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.ARRAY_TYPE,DOMPackage.ARRAY_TYPE__ELEMENT_TYPE),Reltypes.ARRAY_TYPE__ELEMENT_TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.PARAMETERIZED_TYPE,DOMPackage.PARAMETERIZED_TYPE__TYPE),Reltypes.PARAMETERIZED_TYPE__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.PARAMETERIZED_TYPE,DOMPackage.PARAMETERIZED_TYPE__TYPE_ARGUMENTS),Reltypes.PARAMETERIZED_TYPE__TYPE_ARGUMENTS);
					
			mapDOMPackage.put(new Point(DOMPackage.QUALIFIED_TYPE,DOMPackage.QUALIFIED_TYPE__NAME),Reltypes.QUALIFIED_TYPE__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.QUALIFIED_TYPE,DOMPackage.QUALIFIED_TYPE__QUALIFIER),Reltypes.QUALIFIED_TYPE__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.SIMPLE_TYPE,DOMPackage.SIMPLE_TYPE__NAME),Reltypes.SIMPLE_TYPE__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.WILDCARD_TYPE,DOMPackage.WILDCARD_TYPE__BOUND),Reltypes.WILDCARD_TYPE__BOUND);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_VARIABLE_DECLARATION,DOMPackage.SINGLE_VARIABLE_DECLARATION__INITIALIZER),Reltypes.SINGLE_VARIABLE_DECLARATION__INITIALIZER);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_VARIABLE_DECLARATION,DOMPackage.SINGLE_VARIABLE_DECLARATION__NAME),Reltypes.SINGLE_VARIABLE_DECLARATION__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_VARIABLE_DECLARATION,DOMPackage.SINGLE_VARIABLE_DECLARATION__TYPE),Reltypes.SINGLE_VARIABLE_DECLARATION__TYPE);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_VARIABLE_DECLARATION,DOMPackage.SINGLE_VARIABLE_DECLARATION__MODIFIERS),Reltypes.SINGLE_VARIABLE_DECLARATION__MODIFIERS);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_FRAGMENT,DOMPackage.VARIABLE_DECLARATION_FRAGMENT__INITIALIZER),Reltypes.VARIABLE_DECLARATION_FRAGMENT__INITIALIZER);
					
			mapDOMPackage.put(new Point(DOMPackage.VARIABLE_DECLARATION_FRAGMENT,DOMPackage.VARIABLE_DECLARATION_FRAGMENT__NAME),Reltypes.VARIABLE_DECLARATION_FRAGMENT__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.QUALIFIED_NAME,DOMPackage.QUALIFIED_NAME__TYPE_BINDING),Reltypes.QUALIFIED_NAME__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.QUALIFIED_NAME,DOMPackage.QUALIFIED_NAME__NAME),Reltypes.QUALIFIED_NAME__NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.QUALIFIED_NAME,DOMPackage.QUALIFIED_NAME__QUALIFIER),Reltypes.QUALIFIED_NAME__QUALIFIER);
					
			mapDOMPackage.put(new Point(DOMPackage.SIMPLE_NAME,DOMPackage.SIMPLE_NAME__TYPE_BINDING),Reltypes.SIMPLE_NAME__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.MARKER_ANNOTATION,DOMPackage.MARKER_ANNOTATION__TYPE_BINDING),Reltypes.MARKER_ANNOTATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.MARKER_ANNOTATION,DOMPackage.MARKER_ANNOTATION__TYPE_NAME),Reltypes.MARKER_ANNOTATION__TYPE_NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.NORMAL_ANNOTATION,DOMPackage.NORMAL_ANNOTATION__TYPE_BINDING),Reltypes.NORMAL_ANNOTATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.NORMAL_ANNOTATION,DOMPackage.NORMAL_ANNOTATION__TYPE_NAME),Reltypes.NORMAL_ANNOTATION__TYPE_NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.NORMAL_ANNOTATION,DOMPackage.NORMAL_ANNOTATION__VALUES),Reltypes.NORMAL_ANNOTATION__VALUES);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_MEMBER_ANNOTATION,DOMPackage.SINGLE_MEMBER_ANNOTATION__TYPE_BINDING),Reltypes.SINGLE_MEMBER_ANNOTATION__TYPE_BINDING);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_MEMBER_ANNOTATION,DOMPackage.SINGLE_MEMBER_ANNOTATION__TYPE_NAME),Reltypes.SINGLE_MEMBER_ANNOTATION__TYPE_NAME);
					
			mapDOMPackage.put(new Point(DOMPackage.SINGLE_MEMBER_ANNOTATION,DOMPackage.SINGLE_MEMBER_ANNOTATION__VALUE),Reltypes.SINGLE_MEMBER_ANNOTATION__VALUE);
					
			reference2relation.put(DOMPackage.eNS_URI,mapDOMPackage);
					
		}
		
	/**
	* Getting a Relationship from an eRef belonging to 
	* an {@link EObject} eObject
	*@param eObject {@link EObject}
	*@param eRef {@link EReference}
	*@generated
	*/
	//public RelationshipType getReltype(EObject eObject, EReference eRef) {
		//	String key = eObject.eClass().getEPackage().getNsURI();		
			//return getMap().get(key).get(new Point(eObject.eClass().getClassifierID(), eRef.getFeatureID()));
		//}
} 
	
//Reltypes Class
