name: Antora Site Build

on: push

jobs:
  node-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./neoemf-doc
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci --ignore-scripts